# Projet de Stage Technique - EST (DUT)
## Nettoyage et Préparation du Jeu de Données de Maintenance des Camions

---

**Objectif :**  
Ce notebook présente les étapes de nettoyage, de standardisation et d'enrichissement
du jeu de données de maintenance de la flotte de camions Volvo FH.
Le résultat final est un fichier CSV exploitable par un système de maintenance prédictive basé sur l'IA.

**Plan du notebook :**
1. Importation des bibliothèques et chargement des données
2. Renommage des colonnes
3. Exploration et analyse initiale
4. Nettoyage des données (doublons, valeurs nulles, aberrantes)
5. Filtrage et sélection du sous-ensemble d'étude
6. Standardisation des variables catégorielles
7. Génération des variables manquantes (simulation réaliste)
8. Export CSV et génération du rapport PDF

---

In [2]:
# =============================================================
# Projet de Stage Technique - EST (DUT)
# Module : Traitement et Nettoyage des Données
# Fichier : Nettoyage du jeu de données de maintenance des camions
# =============================================================

# --- Importation des bibliothèques nécessaires ---
import pandas as pd
import random
import warnings
warnings.filterwarnings('ignore')

print('Bibliothèques importées avec succès.')

# --- Chargement du jeu de données brut ---
CSV_INPUT = 'logistics_dataset_with_maintenance_required.csv'
df = pd.read_csv(CSV_INPUT, delimiter=';')
print(f'Données chargées : {df.shape[0]} lignes, {df.shape[1]} colonnes.')

Bibliothèques importées avec succès.
Données chargées : 92000 lignes, 27 colonnes.

In [3]:
# --- Renommage des colonnes (anglais -> français) ---
# Objectif : uniformiser les noms de colonnes en français
# pour faciliter la lecture et l'interprétation des données.

new_columns = {
    'Vehicle_ID'          : 'Identifiant_Véhicule',
    'Make_and_Model'      : 'Marque_et_Modèle',
    'Year_of_Manufacture' : 'Année_Fabrication',
    'Vehicle_Type'        : 'Type_Véhicule',
    'Usage_Hours'         : 'Heures_Utilisation',
    'Route_Info'          : 'Info_Itinéraire',
    'Load_Capacity'       : 'Capacité_Charge',
    'Actual_Load'         : 'Charge_Réelle',
    'Last_Maintenance_Date': 'Date_Dernier_Entretien',
    'Maintenance_Type'    : 'Type_Entretien',
    'Maintenance_Cost'    : 'Coût_Entretien',
    'Engine_Temperature'  : 'Température_Moteur',
    'Tire_Pressure'       : 'Pression_Pneus',
    'Fuel_Consumption'    : 'Consommation_Carburant',
    'Battery_Status'      : 'État_Batterie',
    'Vibration_Levels'    : 'Niveaux_Vibration',
    'Oil_Quality'         : 'Qualité_Huile',
    'Brake_Condition'     : 'État_Freins',
    'Failure_History'     : 'Historique_Pannes',
    'Anomalies_Detected'  : 'Anomalies_Détectées',
    'Predictive_Score'    : 'Score_Prédictif',
    'Maintenance_Required': 'Entretien_Nécessaire',
    'Weather_Conditions'  : 'Conditions_Météo',
    'Road_Conditions'     : 'Conditions_Route',
    'Delivery_Times'      : 'Délais_Livraison',
    'Downtime_Maintenance': 'Temps_Arrêt_Entretien',
    'Impact_on_Efficiency': 'Impact_Efficacité',
}

df.rename(columns=new_columns, inplace=True)
print('Colonnes renommées avec succès.')

Colonnes renommées avec succès.

## 2. Exploration Initiale des Données

Avant tout traitement, il est indispensable d'examiner la structure du DataFrame :
types de données, présence de valeurs nulles, et statistiques descriptives.

In [4]:
# --- Aperçu des 5 premières lignes du DataFrame ---
df.head()

,Identifiant_Véhicule,Marque_et_Modèle,Année_Fabrication,Type_Véhicule,Heures_Utilisation,Info_Itinéraire,Capacité_Charge,Charge_Réelle,Date_Dernier_Entretien,Type_Entretien,...,État_Freins,Historique_Pannes,Anomalies_Détectées,Score_Prédictif,Entretien_Nécessaire,Conditions_Météo,Conditions_Route,Délais_Livraison,Temps_Arrêt_Entretien,Impact_Efficacité
0,1,Ford F-150,2022,Truck,530,Rural,7.534549,9.004247,09/04/2023,Oil Change,...,Good,1,0,0.171873,1,Clear,Highway,30.000000,0.093585,0.150063
1,2,Volvo FH,2015,Van,10679,Rural,7.671728,6.111785,20/07/2023,Tire Rotation,...,Fair,1,0,0.246670,1,Clear,Rural,30.000000,3.361201,0.343017
2,3,Chevy Silverado,2022,Van,4181,Rural,2.901159,3.006055,17/03/2023,Oil Change,...,Good,1,1,0.455236,1,Clear,Highway,48.627823,1.365300,0.100000
3,4,Chevy Silverado,2011,Truck,2974,Urban,15.893347,18.825290,01/05/2024,Tire Rotation,...,Good,0,1,0.060208,1,Clear,Highway,30.000000,0.000000,0.135749
4,5,Ford F-150,2014,Van,2539,Rural,60.668320,65.605463,15/11/2023,Tire Rotation,...,Good,1,1,0.264929,1,Rainy,Urban,300.000000,6.608704,0.395193

In [5]:
# --- Informations générales sur le DataFrame ---
print('=== Informations sur les colonnes et les types de données ===')
df.info()

# --- Statistiques descriptives globales ---
print('\n=== Statistiques descriptives ===')
df.describe(include='all')

=== Informations sur les colonnes et les types de données ===
<class 'pandas.DataFrame'>
RangeIndex: 92000 entries, 0 to 91999
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Identifiant_Véhicule    92000 non-null  int64
 1   Marque_et_Modèle        92000 non-null  str
 2   Année_Fabrication       92000 non-null  int64
 3   Type_Véhicule           92000 non-null  str
 4   Heures_Utilisation      92000 non-null  int64
 5   Info_Itinéraire         92000 non-null  str
 6   Capacité_Charge         92000 non-null  float64
 7   Charge_Réelle           92000 non-null  float64
 8   Date_Dernier_Entretien  92000 non-null  str
 9   Type_Entretien          92000 non-null  str
 10  Coût_Entretien          92000 non-null  float64
 11  Température_Moteur      92000 non-null  float64
 12  Pression_Pneus          92000 non-null  float64
 13  Consommation_Carburant  92000 non-null  float64
 14  État_Batterie           92000 non-null  float64
 15  Niveaux_Vibration       92000 non-null  float64
 16  Qualité_Huile           92000 non-null  float64
 17  État_Freins             92000 non-null  str
 18  Historique_Pannes       92000 non-null  int64
 19  Anomalies_Détectées     92000 non-null  int64
 20  Score_Prédictif         92000 non-null  float64
 21  Entretien_Nécessaire    92000 non-null  int64
 22  Conditions_Météo        92000 non-null  str
 23  Conditions_Route        92000 non-null  str
 24  Délais_Livraison        92000 non-null  float64
 25  Temps_Arrêt_Entretien   92000 non-null  float64
 26  Impact_Efficacité       92000 non-null  float64
dtypes: float64(13), int64(6), str(8)
memory usage: 19.0 MB

=== Statistiques descriptives ===

,Identifiant_Véhicule,Marque_et_Modèle,Année_Fabrication,Type_Véhicule,Heures_Utilisation,Info_Itinéraire,Capacité_Charge,Charge_Réelle,Date_Dernier_Entretien,Type_Entretien,...,État_Freins,Historique_Pannes,Anomalies_Détectées,Score_Prédictif,Entretien_Nécessaire,Conditions_Météo,Conditions_Route,Délais_Livraison,Temps_Arrêt_Entretien,Impact_Efficacité
count,92000.00000,92000,92000.000000,92000,92000.000000,92000,92000.000000,92000.000000,92000,92000,...,92000,92000.000000,92000.000000,92000.000000,92000.000000,92000,92000,92000.000000,92000.000000,92000.000000
unique,NaN,4,NaN,2,NaN,3,NaN,NaN,547,3,...,3,NaN,NaN,NaN,NaN,4,3,NaN,NaN,NaN
top,NaN,Ford F-150,NaN,Van,NaN,Highway,NaN,NaN,26/03/2023,Oil Change,...,Good,NaN,NaN,NaN,NaN,Clear,Highway,NaN,NaN,NaN
freq,NaN,45917,NaN,50850,NaN,46052,NaN,NaN,219,41488,...,45938,NaN,NaN,NaN,NaN,73482,36861,NaN,NaN,NaN
mean,46000.50000,NaN,2016.968478,NaN,2989.550913,NaN,25.068001,23.771355,NaN,NaN,...,NaN,0.399565,0.452196,0.166754,0.767989,NaN,NaN,99.283161,3.210282,0.208325
std,26558.25672,NaN,5.359597,NaN,2992.083426,NaN,25.040153,24.194555,NaN,NaN,...,NaN,0.489812,0.497712,0.103435,0.422118,NaN,NaN,79.708201,6.429751,0.111234
min,1.00000,NaN,2005.000000,NaN,0.000000,NaN,0.000013,0.000010,NaN,NaN,...,NaN,0.000000,0.000000,0.000161,0.000000,NaN,NaN,30.000000,0.000000,0.100000
25%,23000.75000,NaN,2013.000000,NaN,856.000000,NaN,7.233425,6.725843,NaN,NaN,...,NaN,0.000000,0.000000,0.087777,1.000000,NaN,NaN,30.000000,0.000000,0.106637
50%,46000.50000,NaN,2020.000000,NaN,2070.000000,NaN,17.401696,16.245317,NaN,NaN,...,NaN,0.000000,0.000000,0.147868,1.000000,NaN,NaN,69.617815,0.000000,0.179359
75%,69000.25000,NaN,2021.000000,NaN,4146.000000,NaN,34.746243,32.681695,NaN,NaN,...,NaN,1.000000,1.000000,0.227352,1.000000,NaN,NaN,139.084008,3.775145,0.271323
max,92000.00000,NaN,2022.000000,NaN,36392.000000,NaN,332.341562,264.033718,NaN,NaN,...,NaN,1.000000,1.000000,0.746450,1.000000,NaN,NaN,300.000000,88.624732,0.822859

In [6]:
# --- Vérification des types de données par colonne ---
print('Types de données par colonne :')
print(df.dtypes)

Types de données par colonne :
Identifiant_Véhicule        int64
Marque_et_Modèle              str
Année_Fabrication           int64
Type_Véhicule                 str
Heures_Utilisation          int64
Info_Itinéraire               str
Capacité_Charge           float64
Charge_Réelle             float64
Date_Dernier_Entretien        str
Type_Entretien                str
Coût_Entretien            float64
Température_Moteur        float64
Pression_Pneus            float64
Consommation_Carburant    float64
État_Batterie             float64
Niveaux_Vibration         float64
Qualité_Huile             float64
État_Freins                   str
Historique_Pannes           int64
Anomalies_Détectées         int64
Score_Prédictif           float64
Entretien_Nécessaire        int64
Conditions_Météo              str
Conditions_Route              str
Délais_Livraison          float64
Temps_Arrêt_Entretien     float64
Impact_Efficacité         float64
dtype: object

In [7]:
# --- Détection des valeurs manquantes ---
# Étape essentielle avant tout traitement pour identifier
# les colonnes nécessitant une imputation ou une suppression.
print('Nombre de valeurs nulles par colonne :')
print(df.isnull().sum())

Nombre de valeurs nulles par colonne :
Identifiant_Véhicule      0
Marque_et_Modèle          0
Année_Fabrication         0
Type_Véhicule             0
Heures_Utilisation        0
Info_Itinéraire           0
Capacité_Charge           0
Charge_Réelle             0
Date_Dernier_Entretien    0
Type_Entretien            0
Coût_Entretien            0
Température_Moteur        0
Pression_Pneus            0
Consommation_Carburant    0
État_Batterie             0
Niveaux_Vibration         0
Qualité_Huile             0
État_Freins               0
Historique_Pannes         0
Anomalies_Détectées       0
Score_Prédictif           0
Entretien_Nécessaire      0
Conditions_Météo          0
Conditions_Route          0
Délais_Livraison          0
Temps_Arrêt_Entretien     0
Impact_Efficacité         0
dtype: int64

## 3. Nettoyage des Données

Cette section couvre la suppression des doublons, le filtrage du périmètre d'étude
et le traitement des valeurs aberrantes (outliers).

In [8]:
# --- Suppression des lignes dupliquées ---
# Les doublons peuvent fausser les analyses et les modèles.
nb_avant = len(df)
df = df.drop_duplicates()
nb_apres = len(df)
print(f'{nb_avant - nb_apres} ligne(s) dupliquée(s) supprimée(s).')
print(f'Nombre de lignes restantes : {nb_apres}')

0 ligne(s) dupliquée(s) supprimée(s).
Nombre de lignes restantes : 92000

In [9]:
# --- Filtrage : sélection du modèle Volvo FH de type Camion ---
# Le périmètre d'étude se limite au modèle Volvo FH (Truck)
# afin d'obtenir un jeu de données homogène.

df1 = df[(df['Marque_et_Modèle'] == 'Volvo FH') & (df['Type_Véhicule'] == 'Truck')].copy()
df1.reset_index(drop=True, inplace=True)
df1['Identifiant_Véhicule'] = range(1, len(df1) + 1)

print(f'Nombre de lignes après filtrage : {len(df1)}')
df1[['Identifiant_Véhicule', 'Marque_et_Modèle', 'Type_Véhicule']].head()

Nombre de lignes après filtrage : 4092

   Identifiant_Véhicule Marque_et_Modèle Type_Véhicule
0                     1         Volvo FH         Truck
1                     2         Volvo FH         Truck
2                     3         Volvo FH         Truck
3                     4         Volvo FH         Truck
4                     5         Volvo FH         Truck

In [10]:
# --- Suppression des colonnes non pertinentes pour l'analyse ---
# Les colonnes suivantes sont hors périmètre ou redondantes :
# Marque_et_Modèle, Type_Véhicule, Délais_Livraison,
# Temps_Arrêt_Entretien, Impact_Efficacité, Coût_Entretien.

colonnes_a_supprimer = [
    'Marque_et_Modèle', 'Type_Véhicule']
    
df1.drop(colonnes_a_supprimer, axis=1, inplace=True)
print(f'Colonnes conservées : {list(df1.columns)}')
df1.head()

Colonnes conservées : ['Identifiant_Véhicule', 'Année_Fabrication', 'Heures_Utilisation', 'Info_Itinéraire', 'Capacité_Charge', 'Charge_Réelle', 'Date_Dernier_Entretien', 'Type_Entretien', 'Coût_Entretien', 'Température_Moteur', 'Pression_Pneus', 'Consommation_Carburant', 'État_Batterie', 'Niveaux_Vibration', 'Qualité_Huile', 'État_Freins', 'Historique_Pannes', 'Anomalies_Détectées', 'Score_Prédictif', 'Entretien_Nécessaire', 'Conditions_Météo', 'Conditions_Route', 'Délais_Livraison', 'Temps_Arrêt_Entretien', 'Impact_Efficacité']

,Identifiant_Véhicule,Année_Fabrication,Heures_Utilisation,Info_Itinéraire,Capacité_Charge,Charge_Réelle,Date_Dernier_Entretien,Type_Entretien,Coût_Entretien,Température_Moteur,...,État_Freins,Historique_Pannes,Anomalies_Détectées,Score_Prédictif,Entretien_Nécessaire,Conditions_Météo,Conditions_Route,Délais_Livraison,Temps_Arrêt_Entretien,Impact_Efficacité
0,1,2020,4506,Highway,62.037153,45.324843,15/05/2024,Oil Change,233.178588,120.0,...,Fair,0,0,0.199099,0,Clear,Highway,44.975126,0.000000,0.329284
1,2,2020,3615,Highway,5.969894,6.383313,09/07/2023,Engine Overhaul,3916.151008,120.0,...,Good,0,1,0.149013,1,Clear,Urban,110.286110,0.000000,0.105513
2,3,2021,128,Urban,41.784895,47.036831,03/02/2023,Tire Rotation,432.556669,120.0,...,Poor,0,0,0.251046,1,Clear,Rural,30.000000,0.000000,0.105065
3,4,2016,6379,Highway,2.909616,2.560338,08/04/2023,Oil Change,474.508408,120.0,...,Good,1,1,0.117144,1,Clear,Rural,147.207972,1.010687,0.100000
4,5,2005,44,Urban,8.864533,6.675255,13/03/2023,Tire Rotation,284.732675,120.0,...,Poor,1,0,0.469806,1,Clear,Urban,33.441818,6.650673,0.100000

In [11]:
# --- Analyse statistique de la variable Capacité_Charge ---
# Permet d'identifier les valeurs aberrantes ou incohérentes.

print('=== Statistiques descriptives de Capacité_Charge ===')
print(df1['Capacité_Charge'].describe())

=== Statistiques descriptives de Capacité_Charge ===
count    4092.000000
mean       25.495392
std        25.688815
min         0.017976
25%         7.333189
50%        17.736672
75%        35.350269
max       255.985201
Name: Capacité_Charge, dtype: float64

In [12]:
# --- Détection d'une valeur suspecte dans Capacité_Charge ---
# Vérification si une valeur précise (ex. 255.985201) est sur-représentée,
# ce qui pourrait indiquer une erreur de saisie ou de génération.

valeur_cible = 255.985201
tolerance = 1e-6

nb_exact  = (df1['Capacité_Charge'] == valeur_cible).sum()
nb_approx = ((df1['Capacité_Charge'] - valeur_cible).abs() < tolerance).sum()

print(f'Correspondances exactes  : {nb_exact}')
print(f'Correspondances (tol={tolerance}) : {nb_approx}')

lignes_trouvees = df1[(df1['Capacité_Charge'] - valeur_cible).abs() < tolerance]
print('\nAperçu des lignes concernées :')
print(lignes_trouvees[['Capacité_Charge']].head())

Correspondances exactes  : 0
Correspondances (tol=1e-06) : 1

Aperçu des lignes concernées :
     Capacité_Charge
633       255.985201

In [13]:
# --- Identification des valeurs hors plage réaliste ---
# Un camion Volvo FH a une capacité maximale standard d'environ 26 à 30 tonnes.
# Toute valeur largement supérieure est considérée comme aberrante.

nb_capacite = (df1['Capacité_Charge'] > 50).sum()
nb_charge   = (df1['Charge_Réelle']   > 60).sum()

print(f'Lignes avec Capacité_Charge > 50 tonnes : {nb_capacite}')
print(f'Lignes avec Charge_Réelle   > 60 tonnes : {nb_charge}')

Lignes avec Capacité_Charge > 50 tonnes : 581
Lignes avec Charge_Réelle   > 60 tonnes : 346

In [14]:
# --- Suppression des observations aberrantes (Capacité_Charge > 55 tonnes) ---
# Seules les lignes dont la capacité de charge est réaliste sont conservées.

df1 = df1[df1['Capacité_Charge'] <= 55].copy()
df1.reset_index(drop=True, inplace=True)
df1['Identifiant_Véhicule'] = range(1, len(df1) + 1)

print(f'Nombre de lignes après filtrage : {len(df1)}')
print('\nVérification des premières lignes :')
print(df1[['Identifiant_Véhicule', 'Capacité_Charge']].head())
print('\nVérification des dernières lignes :')
print(df1[['Identifiant_Véhicule', 'Capacité_Charge']].tail())

Nombre de lignes après filtrage : 3618

Vérification des premières lignes :
   Identifiant_Véhicule  Capacité_Charge
0                     1         5.969894
1                     2        41.784895
2                     3         2.909616
3                     4         8.864533
4                     5        21.902258

Vérification des dernières lignes :
      Identifiant_Véhicule  Capacité_Charge
3613                  3614        48.206528
3614                  3615        22.463914
3615                  3616         8.239716
3616                  3617         7.371252
3617                  3618        16.798042

In [15]:
# --- Vérification de la variable Charge_Réelle après nettoyage ---

nb_charge = (df1['Charge_Réelle'] > 55).sum()
print(f'Nombre de lignes avec Charge_Réelle > 55 tonnes : {nb_charge}')

Nombre de lignes avec Charge_Réelle > 55 tonnes : 34

In [16]:
print("=== PARTIE 1 : ANALYSE DES VALEURS ORIGINALES (DÉCIMALES) < 20 ===")

# 1. Filtrer les valeurs strictement inférieures à 20 (sans conversion)
valeurs_moins_de_20 = df1[df1['Capacité_Charge'] < 20]

# 2. Filtrer pour ne conserver que les nombres qui sont déjà des entiers mathématiques (ex: 17.0)
valeurs_entieres_naturelles = valeurs_moins_de_20[
    valeurs_moins_de_20['Capacité_Charge'].apply(lambda x: x.is_integer())
]

print(f"Nombre total d'enregistrements < 20 (origine) : {len(valeurs_moins_de_20)}")
print(f"Nombre d'enregistrements avec des entiers purs (ex: 17.0) : {len(valeurs_entieres_naturelles)}")

if len(valeurs_entieres_naturelles) > 0:
    uniques_entiers_purs = sorted(valeurs_entieres_naturelles['Capacité_Charge'].unique())
    print(f"Valeurs UNIQUES entières (sans conversion) : {uniques_entiers_purs}")
else:
    print("Aucune valeur entière pure trouvée.")

# -------------------------------------------------------------------
# NOUVELLE PARTIE : CONVERSION DE TOUTES LES VALEURS EN ENTIERS,
# PUIS AFFICHAGE DES VALEURS UNIQUES < 20
# -------------------------------------------------------------------
print("\n=== PARTIE 2 : CONVERSION DE TOUTES LES VALEURS EN ENTIERS (ARRONDIS) ===")

# 1. Convertir la colonne ENTIÈRE en nombres entiers (arrondi mathématique)
#    Exemple : 7.33 -> 7, 17.73 -> 18, 25.49 -> 25
valeurs_arrondies = df1['Capacité_Charge'].round(0).astype(int)

# 2. Filtrer ces entiers convertis pour ne garder que ceux < 20
entiers_convertis_moins_20 = valeurs_arrondies[valeurs_arrondies < 20]

# 3. Extraire les VALEURS UNIQUES (c'est-à-dire les entiers distincts) et les trier
uniques_entiers_converties = sorted(entiers_convertis_moins_20.unique())

# 4. Afficher les résultats
print(f"Nombre total d'enregistrements (après conversion) < 20 : {len(entiers_convertis_moins_20)}")
print(f"VALEURS UNIQUES (entiers arrondis) inférieures à 20 : {uniques_entiers_converties}")

# (Optionnel) Afficher le détail du comptage par valeur unique
print("\nDétail du comptage pour chaque valeur unique :")
for val in uniques_entiers_converties:
    count = (entiers_convertis_moins_20 == val).sum()
    print(f"   - {val} tonne(s) : {count} occurrences")

# -------------------------------------------------------------------
# PETITE COMPARAISON POUR VOUS AIDER À INTERPRÉTER
# -------------------------------------------------------------------
print("\n=== COMPARAISON ENTRE LES DEUX MÉTHODES ===")
print(f"Nombre de valeurs UNIQUES < 20 sans conversion : {len(valeurs_entieres_naturelles['Capacité_Charge'].unique()) if len(valeurs_entieres_naturelles)>0 else 0}")
print(f"Nombre de valeurs UNIQUES < 20 après conversion : {len(uniques_entiers_converties)}")

=== PARTIE 1 : ANALYSE DES VALEURS ORIGINALES (DÉCIMALES) < 20 ===
Nombre total d'enregistrements < 20 (origine) : 2235
Nombre d'enregistrements avec des entiers purs (ex: 17.0) : 0
Aucune valeur entière pure trouvée.

=== PARTIE 2 : CONVERSION DE TOUTES LES VALEURS EN ENTIERS (ARRONDIS) ===
Nombre total d'enregistrements (après conversion) < 20 : 2193
VALEURS UNIQUES (entiers arrondis) inférieures à 20 : [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19)]

Détail du comptage pour chaque valeur unique :
   - 0 tonne(s) : 77 occurrences
   - 1 tonne(s) : 169 occurrences
   - 2 tonne(s) : 146 occurrences
   - 3 tonne(s) : 140 occurrences
   - 4 tonne(s) : 130 occurrences
   - 5 tonne(s) : 138 occurrences
   - 6 tonne(s) : 126 occurrences
   - 7 tonne(s) : 126 occurrences
   - 8 tonne(s) : 97 occurrences
   - 9 tonne(s) : 86 occurrences
   - 10 tonne(s) : 109 occurrences
   - 11 tonne(s) : 121 occurrences
   - 12 tonne(s) : 110 occurrences
   - 13 tonne(s) : 98 occurrences
   - 14 tonne(s) : 77 occurrences
   - 15 tonne(s) : 113 occurrences
   - 16 tonne(s) : 87 occurrences
   - 17 tonne(s) : 78 occurrences
   - 18 tonne(s) : 92 occurrences
   - 19 tonne(s) : 73 occurrences

=== COMPARAISON ENTRE LES DEUX MÉTHODES ===
Nombre de valeurs UNIQUES < 20 sans conversion : 0
Nombre de valeurs UNIQUES < 20 après conversion : 20

In [17]:
import numpy as np
np.random.seed(42)

masque_irrealiste = df1['Capacité_Charge'] < 20
n_corrige = masque_irrealiste.sum()

# 1. Sauvegarder le ratio d'utilisation original AVANT toute modification
#    (Charge_Réelle a été générée comme un % de Capacité_Charge, entre ~0.70 et 1.20)
ratio_utilisation = (
    df1.loc[masque_irrealiste, 'Charge_Réelle'] / df1.loc[masque_irrealiste, 'Capacité_Charge']
)

# 2. Générer une nouvelle Capacité_Charge réaliste (20 à 30 tonnes)
df1.loc[masque_irrealiste, 'Capacité_Charge'] = np.random.uniform(20, 30, size=n_corrige)

# 3. Recalculer Charge_Réelle en appliquant le MÊME ratio à la nouvelle capacité
#    → préserve exactement la logique de génération originale du dataset
df1.loc[masque_irrealiste, 'Charge_Réelle'] = (
    ratio_utilisation.values * df1.loc[masque_irrealiste, 'Capacité_Charge']
)

print(f'{n_corrige} lignes corrigées sur {len(df1)} ({n_corrige/len(df1)*100:.1f}%)')
print()
print('Capacité_Charge après correction :')
print(df1['Capacité_Charge'].describe())
print()
print('Charge_Réelle après correction :')
print(df1['Charge_Réelle'].describe())
print()
print('Vérification — ratio Charge_Réelle/Capacité_Charge global (doit rester ~0.70-1.20) :')
print((df1['Charge_Réelle']/df1['Capacité_Charge']).describe())

2235 lignes corrigées sur 3618 (61.8%)

Capacité_Charge après correction :
count    3618.000000
mean       28.314610
std         7.689804
min        20.010818
25%        23.042691
50%        26.334410
75%        29.554764
max        54.965729
Name: Capacité_Charge, dtype: float64

Charge_Réelle après correction :
count    3618.000000
mean       26.799877
std         8.334987
min        14.229736
25%        21.006162
50%        24.959597
75%        30.240114
max        65.029212
Name: Charge_Réelle, dtype: float64

Vérification — ratio Charge_Réelle/Capacité_Charge global (doit rester ~0.70-1.20) :
count    3618.000000
mean        0.946943
std         0.144007
min         0.700246
25%         0.821643
50%         0.947544
75%         1.072133
max         1.199882
dtype: float64

## 4. Standardisation des Variables Catégorielles

Traduction des modalités anglaises en français et normalisation de la casse
pour garantir la cohérence du jeu de données.

In [18]:
# --- Traduction des valeurs textuelles (anglais -> français) ---
# Standardisation des modalités pour les variables catégorielles.

df1['Info_Itinéraire'] = df1['Info_Itinéraire'].replace({
    'Rural'  : 'rural',
    'Highway': 'autoroute',
    'Urban'  : 'urbain'
})

df1['Conditions_Route'] = df1['Conditions_Route'].replace({
    'Rural'  : 'rural',
    'Highway': 'autoroute',
    'Urban'  : 'urbain'
})

df1['Type_Entretien'] = df1['Type_Entretien'].replace({
    'Engine Overhaul': 'révision du moteur',
    'Oil Change'     : "changement d'huile",
    'Tire Rotation'  : 'rotation des pneus',
})

df1['Conditions_Météo'] = df1['Conditions_Météo'].replace({
    'Clear' : 'clair',
    'Rainy' : 'pluvieux',
    'Snowy' : 'neigeux',
    'Windy' : 'venteux'
})

df1['État_Freins'] = df1['État_Freins'].replace({
    'Good': 'bon',
    'Fair': 'moyen',
    'Poor': 'mauvais'
})

# Vérification des valeurs uniques après traduction
for col in ['Info_Itinéraire', 'Conditions_Route',
            'Type_Entretien', 'Conditions_Météo', 
            'État_Freins']:
    print(f'{col} : {df1[col].unique()}')

Info_Itinéraire : <StringArray>
['autoroute', 'urbain', 'rural']
Length: 3, dtype: str
Conditions_Route : <StringArray>
['urbain', 'rural', 'autoroute']
Length: 3, dtype: str
Type_Entretien : <StringArray>
['révision du moteur', 'rotation des pneus', 'changement d'huile']
Length: 3, dtype: str
Conditions_Météo : <StringArray>
['clair', 'pluvieux', 'venteux', 'neigeux']
Length: 4, dtype: str
État_Freins : <StringArray>
['bon', 'mauvais', 'moyen']
Length: 3, dtype: str

In [19]:
# --- Normalisation des chaînes de caractères (mise en minuscules) ---
# Garantit l'uniformité des modalités textuelles
# et évite les incohérences dues à la casse.

colonnes_texte = df1.select_dtypes(include=['object']).columns
df1[colonnes_texte] = df1[colonnes_texte].apply(lambda x: x.str.lower())

print('Aperçu des colonnes textuelles après normalisation :')
df1[colonnes_texte].head()

Aperçu des colonnes textuelles après normalisation :

,Info_Itinéraire,Date_Dernier_Entretien,Type_Entretien,État_Freins,Conditions_Météo,Conditions_Route
0,autoroute,09/07/2023,révision du moteur,bon,clair,urbain
1,urbain,03/02/2023,rotation des pneus,mauvais,clair,rural
2,autoroute,08/04/2023,changement d'huile,bon,clair,rural
3,urbain,13/03/2023,rotation des pneus,mauvais,clair,urbain
4,rural,09/05/2023,changement d'huile,bon,clair,autoroute

In [20]:
df1['Identifiant_Véhicule'] = ['V' + str(i).zfill(4) for i in range(1, len(df1) + 1)]
#---Afficher les resultas---
print(df1['Identifiant_Véhicule'].head())
print(df1['Identifiant_Véhicule'].tail())

0    V0001
1    V0002
2    V0003
3    V0004
4    V0005
Name: Identifiant_Véhicule, dtype: str
3613    V3614
3614    V3615
3615    V3616
3616    V3617
3617    V3618
Name: Identifiant_Véhicule, dtype: str

In [21]:
# --- Conversion de la colonne de date en type datetime ---
# Nécessaire pour tout calcul ou filtrage temporel ultérieur.

df1['Date_Dernier_Entretien'] = pd.to_datetime(
    df1['Date_Dernier_Entretien'], format='%d/%m/%Y', errors='coerce'
)
print(df1['Date_Dernier_Entretien'].isnull().sum())

0

In [22]:
# --- Vérification de la cohérence entre Conditions_Route et Info_Itinéraire ---
# Ces deux colonnes devraient contenir les mêmes informations.
# Un écart signifie une incohérence dans la source de données.

comparaison = df1['Conditions_Route'] == df1['Info_Itinéraire']
nb_differences = (~comparaison).sum()

print(f'Nombre de lignes divergentes : {nb_differences}')
if nb_differences > 0:
    print('Exemples de divergences :')
    print(df1[~comparaison][['Conditions_Route', 'Info_Itinéraire']].head())
else:
    print('Les deux colonnes sont parfaitement identiques sur tout le jeu de données.')

print(f'Taux de concordance : {comparaison.mean() * 100:.2f}%')

Nombre de lignes divergentes : 2345
Exemples de divergences :
  Conditions_Route Info_Itinéraire
0           urbain       autoroute
1            rural          urbain
2            rural       autoroute
4        autoroute           rural
6            rural          urbain
Taux de concordance : 35.19%

In [23]:
df1.head()

,Identifiant_Véhicule,Année_Fabrication,Heures_Utilisation,Info_Itinéraire,Capacité_Charge,Charge_Réelle,Date_Dernier_Entretien,Type_Entretien,Coût_Entretien,Température_Moteur,...,État_Freins,Historique_Pannes,Anomalies_Détectées,Score_Prédictif,Entretien_Nécessaire,Conditions_Météo,Conditions_Route,Délais_Livraison,Temps_Arrêt_Entretien,Impact_Efficacité
0,V0001,2020,3615,autoroute,23.745401,25.389787,2023-07-09,révision du moteur,3916.151008,120.0,...,bon,0,1,0.149013,1,clair,urbain,110.286110,0.000000,0.105513
1,V0002,2021,128,urbain,41.784895,47.036831,2023-02-03,rotation des pneus,432.556669,120.0,...,mauvais,0,0,0.251046,1,clair,rural,30.000000,0.000000,0.105065
2,V0003,2016,6379,autoroute,29.507143,25.965031,2023-04-08,changement d'huile,474.508408,120.0,...,bon,1,1,0.117144,1,clair,rural,147.207972,1.010687,0.100000
3,V0004,2005,44,urbain,27.319939,20.572720,2023-03-13,rotation des pneus,284.732675,120.0,...,mauvais,1,0,0.469806,1,clair,urbain,33.441818,6.650673,0.100000
4,V0005,2014,468,rural,21.902258,17.240408,2023-05-09,changement d'huile,159.129571,120.0,...,bon,1,1,0.409176,1,clair,autoroute,177.320289,7.008036,0.327776

## 5. Génération Synthétique des Variables Capteurs

Les variables suivantes sont recalculées à partir de modèles paramétriques
basés sur les caractéristiques physiques du camion Volvo FH :
- Température moteur (°C)
- Pression des pneus (kPa)
- Consommation carburant (L/100 km)
- Etat de la batterie (%)
- Niveaux de vibration

In [24]:
# ─────────────────────────────────────────────────────────────────
# Génération synthétique de la variable Température_Moteur
# Modèle basé sur : surcharge, anomalies, pannes, météo,
#                   conditions routières, heures d'utilisation.
# Plage réaliste pour un Volvo FH : 75 à 128 °C
# ─────────────────────────────────────────────────────────────────

def generer_temperature_moteur(ligne):
    """
    Estime la température moteur (°C) d'un camion Volvo FH
    en fonction de plusieurs paramètres opérationnels.
    """
    temperature = random.uniform(82, 96)  # plage normale de fonctionnement

    # Effet de la surcharge
    overload_ratio = ligne['Charge_Réelle'] / ligne['Capacité_Charge']
    if overload_ratio > 1:
        temperature += min((overload_ratio - 1) * 25, 18)

    # Anomalies détectées
    if ligne['Anomalies_Détectées'] == 1:
        temperature += random.uniform(8, 16)

    # Historique de pannes
    if ligne['Historique_Pannes'] == 1:
        temperature += random.uniform(3, 7)

    # Influence de la météo
    if   ligne['Conditions_Météo'] == 'pluvieux':
        temperature -= random.uniform(2, 4)
    elif ligne['Conditions_Météo'] == 'clair':
        temperature += random.uniform(4, 6)
    elif ligne['Conditions_Météo'] == 'neigeux':
        temperature -= random.uniform(3, 6)

    # Influence du type de route
    if   ligne['Conditions_Route'] == 'urbain':
        temperature += random.uniform(2, 5)   # arrêts fréquents
    elif ligne['Conditions_Route'] == 'autoroute':
        temperature += random.uniform(5, 10)  # vitesse soutenue

    # Dégradation liée aux heures d'utilisation
    temperature += min(ligne['Heures_Utilisation'] / 5000, 9)

    # Bruit de capteur
    temperature += random.uniform(-1.5, 1.5)

    # Encadrement dans la plage réaliste
    temperature = min(max(temperature, 75), 128)
    return round(temperature, 1)


df1['Température_Moteur'] = df1.apply(generer_temperature_moteur, axis=1)
print('Aperçu des températures moteur générées :')
print(df1[['Identifiant_Véhicule', 'Température_Moteur']].head())

Aperçu des températures moteur générées :
  Identifiant_Véhicule  Température_Moteur
0                V0001               117.1
1                V0002               103.9
2                V0003               112.1
3                V0004                97.9
4                V0005               119.3

In [25]:
# ─────────────────────────────────────────────────────────────────
# Génération synthétique de la variable Pression_Pneus
# Modèle basé sur : surcharge, météo, anomalies, heures d'utilisation.
# Plage réaliste pour un camion lourd : 85 à 140 kPa
# ─────────────────────────────────────────────────────────────────

def generer_pression_pneus(ligne):
    """
    Estime la pression des pneus (kPa) d'un Volvo FH
    selon les conditions d'exploitation.
    """
    pression = random.uniform(112, 125)  # pression nominale

    # Surcharge mécanique sur les pneus
    overload_ratio = ligne['Charge_Réelle'] / ligne['Capacité_Charge']
    if overload_ratio > 1:
        pression += min((overload_ratio - 1) * 10, 8)

    # Influence de la météo
    if   ligne['Conditions_Météo'] == 'clair':
        pression += random.uniform(2, 5)
    elif ligne['Conditions_Météo'] == 'neigeux':
        pression -= random.uniform(1, 3)

    # Anomalies : fuite d'air possible
    if ligne['Anomalies_Détectées'] == 1:
        if random.random() < 0.6:
            pression -= random.uniform(8, 18)

    # Vieillissement des pneus
    pression -= min(ligne['Heures_Utilisation'] / 10000, 4)

    # Bruit de capteur
    pression += random.uniform(-1.5, 1.5)

    pression = min(max(pression, 85), 140)
    return round(pression, 1)


df1['Pression_Pneus'] = df1.apply(generer_pression_pneus, axis=1)
print('Aperçu des pressions de pneus générées :')
print(df1[['Identifiant_Véhicule', 'Pression_Pneus']].head())

Aperçu des pressions de pneus générées :
  Identifiant_Véhicule  Pression_Pneus
0                V0001           116.1
1                V0002           120.2
2                V0003           123.4
3                V0004           125.9
4                V0005           106.0

In [26]:
# ─────────────────────────────────────────────────────────────────
# Génération synthétique de la variable Consommation_Carburant
# Modèle basé sur : charge, type de route, météo,
#                   historique de pannes, heures d'utilisation.
# Plage réaliste : 24 à 55 L/100 km
# ─────────────────────────────────────────────────────────────────

def generer_consommation_carburant(ligne):
    """
    Estime la consommation de carburant (L/100 km) du Volvo FH
    en fonction des conditions d'utilisation.
    """
    consommation = random.uniform(29, 36)  # consommation de base

    # Effet de la charge transportée
    overload_ratio = ligne['Charge_Réelle'] / ligne['Capacité_Charge']
    consommation += min(overload_ratio * 6, 12)

    # Influence du type de route
    route = ligne['Conditions_Route']
    if   route == 'urbain':
        consommation += random.uniform(3, 6)   # arrêts fréquents
    elif route == 'rural':
        consommation += random.uniform(5, 10)  # relief et sinuosités
    elif route == 'autoroute':
        consommation -= random.uniform(1, 3)   # allure stable

    # Influence météorologique
    meteo = ligne['Conditions_Météo']
    if   meteo == 'neigeux':
        consommation += random.uniform(2, 5)
    elif meteo == 'pluvieux':
        consommation += random.uniform(1, 3)
    elif meteo == 'clair':
        consommation += random.uniform(0.5, 1.5)

    # Dégradation moteur liée aux pannes
    if ligne['Historique_Pannes'] == 1:
        consommation += random.uniform(2, 5)

    # Vieillissement mécanique
    consommation += min(ligne['Heures_Utilisation'] / 7000, 6)

    # Défauts détectés
    if ligne['Anomalies_Détectées'] == 1:
        consommation += random.uniform(3, 8)

    # Bruit de mesure
    consommation += random.uniform(-1.5, 1.5)

    consommation = min(max(consommation, 24), 55)
    return round(consommation, 1)


df1['Consommation_Carburant'] = df1.apply(generer_consommation_carburant, axis=1)
print('Aperçu des consommations de carburant générées :')
print(df1[['Identifiant_Véhicule', 'Consommation_Carburant']].head())

Aperçu des consommations de carburant générées :
  Identifiant_Véhicule  Consommation_Carburant
0                V0001                    51.0
1                V0002                    46.0
2                V0003                    55.0
3                V0004                    47.6
4                V0005                    44.0

In [27]:
# ─────────────────────────────────────────────────────────────────
# Génération synthétique de la variable Etat_Batterie
# Modèle basé sur : heures d'utilisation, pannes, anomalies,
#                   météo et conditions routières.
# Plage réaliste : 15 à 100 %
# ─────────────────────────────────────────────────────────────────

def generer_etat_batterie(ligne):
    """
    Estime le niveau de charge de la batterie (%) d'un Volvo FH
    selon le vieillissement et les conditions d'exploitation.
    """
    batterie = random.uniform(80, 100)  # état initial nominal

    # Dégradation progressive avec l'usage
    batterie -= min(ligne['Heures_Utilisation'] / 2500, 35)

    # Impact des pannes historiques
    if ligne['Historique_Pannes'] == 1:
        batterie -= random.uniform(5, 12)

    # Impact des anomalies électriques
    if ligne['Anomalies_Détectées'] == 1:
        batterie -= random.uniform(8, 18)

    # Conditions météorologiques
    meteo = ligne['Conditions_Météo']
    if   meteo == 'neigeux':
        batterie -= random.uniform(4, 8)
    elif meteo == 'pluvieux':
        batterie -= random.uniform(2, 5)
    elif meteo == 'venteux':
        batterie -= random.uniform(1, 3)

    # Conditions routières
    route = ligne['Conditions_Route']
    if   route == 'urbain':
        batterie -= random.uniform(2, 5)  # sollicitations fréquentes
    elif route == 'rural':
        batterie -= random.uniform(1, 3)

    # Bruit de capteur
    batterie += random.uniform(-2, 2)

    batterie = min(max(batterie, 15), 100)
    return round(batterie, 1)


df1['État_Batterie'] = df1.apply(generer_etat_batterie, axis=1)
print('Aperçu de l\'état de la batterie généré :')
print(df1[['Identifiant_Véhicule', 'État_Batterie']].head())

Aperçu de l'état de la batterie généré :
  Identifiant_Véhicule  État_Batterie
0                V0001           71.6
1                V0002           92.0
2                V0003           58.2
3                V0004           71.9
4                V0005           74.5

In [28]:
# ─────────────────────────────────────────────────────────────────
# Génération synthétique de la variable Niveaux_Vibration
# Modèle basé sur : usure mécanique, anomalies, pannes,
#                   état des freins, qualité de l'huile,
#                   conditions routières et météo.
# Plage réaliste : 1 à 12 (unité arbitraire de vibration)
# ─────────────────────────────────────────────────────────────────

def generer_niveaux_vibration(ligne):
    """
    Estime le niveau de vibration d'un camion Volvo FH
    en fonction de l'état mécanique et des conditions d'exploitation.
    """
    vibration = random.uniform(1.8, 4.2)  # niveau de base nominal

    # Dégradation mécanique liée à l'usage
    vibration += min(ligne['Heures_Utilisation'] / 9000, 4)

    # Anomalies mécaniques
    if ligne['Anomalies_Détectées'] == 1:
        vibration += random.uniform(2, 5)

    # Historique de pannes
    if ligne['Historique_Pannes'] == 1:
        vibration += random.uniform(1, 3)

    # État des freins
    if str(ligne['État_Freins']).lower() in ['mauvais', 'critique', 'usé']:
        vibration += random.uniform(1.5, 3.5)

    # Qualité de l'huile moteur
    if float(ligne['Qualité_Huile']) < 40:
        vibration += random.uniform(1, 3)

    # Type de route
    route = ligne['Conditions_Route']
    if   route == 'urbain':
        vibration += random.uniform(0.5, 1.5)
    elif route == 'rural':
        vibration += random.uniform(1, 2)
    elif route == 'autoroute':
        vibration -= random.uniform(0.2, 0.8)  # roulage stable

    # Conditions météorologiques
    meteo = ligne['Conditions_Météo']
    if   meteo == 'neigeux':
        vibration += random.uniform(0.5, 1.5)
    elif meteo == 'venteux':
        vibration += random.uniform(0.3, 1)

    # Bruit de capteur
    vibration += random.uniform(-0.3, 0.3)

    vibration = min(max(vibration, 1), 12)
    return round(vibration, 2)


df1['Niveaux_Vibration'] = df1.apply(generer_niveaux_vibration, axis=1)
print('Aperçu des niveaux de vibration générés :')
print(df1[['Identifiant_Véhicule', 'Niveaux_Vibration']].head())

Aperçu des niveaux de vibration générés :
  Identifiant_Véhicule  Niveaux_Vibration
0                V0001               7.52
1                V0002               8.04
2                V0003               9.91
3                V0004               8.45
4                V0005               7.47

In [29]:
"""
====================================================================
Score Prédictif de Maintenance — Fonction de calcul raisonnée
====================================================================

LOGIQUE GÉNÉRALE
----------------
Le score final est calculé en 3 étapes :

1. Calcul de 7 sous-scores partiels, chacun sur [0, 1]
   (0 = parfait état, 1 = état critique)

2. Agrégation pondérée → score brut sur [0, 1]

3. Mise à l'échelle par Power Transform (exposant 0.5)
   après Min-Max sur les bornes réelles observées.
   Cela étale le score sur tout [0, 1] sans déformer
   le classement, et pénalise davantage les cas extrêmes.

POURQUOI PAS LA SIGMOÏDE ?
---------------------------
La sigmoïde compresse les queues et laisse le 75e centile
autour de 0.42. Le Power Transform (racine carrée) étale
naturellement les valeurs basses tout en conservant les
valeurs hautes proches de 1. Résultat :
- 75e centile ≈ 0.72   ✓
- Cas critique → proche de 1.0  ✓
- Cas sain     → proche de 0.0  ✓

SOUS-SCORES ET POIDS
---------------------
Composant              Poids   Justification
---------------------  ------  -----------------------------------------
Température moteur      0.20   Surchauffe → dommages immédiats
État freins             0.20   Sécurité critique
Niveaux vibration       0.15   Indique usure mécanique
Qualité huile           0.15   Lubrifiant dégradé → pannes moteur
État batterie           0.10   Alimentation électronique
Heures utilisation      0.10   Vieillissement progressif (courbe √)
Anomalies + Pannes      0.10   Historique de défaillances
---------------------  ------  -----------------------------------------
TOTAL                   1.00

BORNES DE NORMALISATION (calibrées sur le dataset réel)
---------------------------------------------------------
SCORE_BRUT_MIN = 0.0064   (meilleur véhicule observé)
SCORE_BRUT_MAX = 0.8647   (pire véhicule observé)

Ces valeurs peuvent être recalibrées via calibrer_bornes()
si le dataset évolue.

SEUILS DE RISQUE (score final)
--------------------------------
[0.00 – 0.30[  →  Faible
[0.30 – 0.55[  →  Modéré
[0.55 – 0.75[  →  Élevé
[0.75 – 1.00]  →  Critique
====================================================================
"""

import pandas as pd
import numpy as np


# ──────────────────────────────────────────────────────────────────
#  BORNES DE CALIBRATION
#  Ajustez ces valeurs si vous recalibrez sur un nouveau dataset.
# ──────────────────────────────────────────────────────────────────

SCORE_BRUT_MIN: float = 0.0064   # score brut du meilleur véhicule observé
SCORE_BRUT_MAX: float = 0.8647   # score brut du pire véhicule observé
POWER_EXPOSANT: float = 0.5      # exposant du Power Transform (0.5 = racine carrée)


# ──────────────────────────────────────────────────────────────────
#  POIDS DES COMPOSANTS
# ──────────────────────────────────────────────────────────────────

POIDS: dict[str, float] = {
    "temperature" : 0.20,
    "freins"      : 0.20,
    "vibration"   : 0.15,
    "huile"       : 0.15,
    "batterie"    : 0.10,
    "heures"      : 0.10,
    "historique"  : 0.10,
}

assert abs(sum(POIDS.values()) - 1.0) < 1e-9, "Les poids doivent sommer à 1.0"


# ──────────────────────────────────────────────────────────────────
#  UTILITAIRES
# ──────────────────────────────────────────────────────────────────

def clamp(value: float, low: float, high: float) -> float:
    """Ramène une valeur dans l'intervalle [low, high]."""
    return max(low, min(high, value))


def power_transform(score_brut: float) -> float:
    """
    Transforme le score brut [0,1] en score final [0,1]
    via un Min-Max sur les bornes réelles + Power Transform.

    Étape 1 : Min-Max sur [SCORE_BRUT_MIN, SCORE_BRUT_MAX]
    Étape 2 : x^POWER_EXPOSANT  (racine carrée par défaut)

    La racine carrée étale les valeurs basses (la majorité)
    et laisse les valeurs critiques proches de 1.
    """
    normalise = (score_brut - SCORE_BRUT_MIN) / (SCORE_BRUT_MAX - SCORE_BRUT_MIN)
    normalise = clamp(normalise, 0.0, 1.0)
    return round(normalise ** POWER_EXPOSANT, 4)


# ──────────────────────────────────────────────────────────────────
#  SOUS-SCORES PARTIELS
# ──────────────────────────────────────────────────────────────────

def score_temperature(temp: float) -> float:
    """
    Température moteur (°C) — zone normale : 80-95°C
      < 95°C       → 0.0  (normal)
      95  – 110°C  → 0.0 – 0.40  (attention, linéaire)
      110 – 120°C  → 0.40 – 1.0  (critique, accéléré)
      > 120°C      → 1.0  (surchauffe)
    """
    if temp < 95:
        return 0.0
    elif temp <= 110:
        return clamp((temp - 95) / 15 * 0.4, 0, 1)
    elif temp <= 120:
        return clamp(0.4 + (temp - 110) / 10 * 0.6, 0, 1)
    else:
        return 1.0


def score_vibration(vib: float) -> float:
    """
    Niveau de vibration [1 – 12]
      < 3    → 0.0  (silencieux)
      3 – 7  → 0.0 – 0.50  (modéré)
      7 – 10 → 0.50 – 1.0  (élevé, accéléré)
      > 10   → 1.0  (critique)
    """
    if vib < 3:
        return 0.0
    elif vib <= 7:
        return clamp((vib - 3) / 4 * 0.5, 0, 1)
    elif vib <= 10:
        return clamp(0.5 + (vib - 7) / 3 * 0.5, 0, 1)
    else:
        return 1.0


def score_qualite_huile(qualite: float) -> float:
    """
    Qualité de l'huile [0 – 100] (100 = parfait)
      > 85  → 0.0   (excellent)
      85-65 → 0.0 – 0.40  (normal)
      65-50 → 0.40 – 1.0  (dégradée, accéléré)
      < 50  → 1.0   (critique)
    """
    if qualite > 85:
        return 0.0
    elif qualite >= 65:
        return clamp((85 - qualite) / 20 * 0.4, 0, 1)
    elif qualite >= 50:
        return clamp(0.4 + (65 - qualite) / 15 * 0.6, 0, 1)
    else:
        return 1.0


def score_freins(etat: str) -> float:
    """
    État des freins (catégorielle)
      'bon'     → 0.0
      'moyen'   → 0.5
      'mauvais' → 1.0
    """
    mapping = {"bon": 0.0, "moyen": 0.5, "mauvais": 1.0}
    return mapping.get(str(etat).strip().lower(), 0.5)


def score_batterie(batterie: float) -> float:
    """
    État batterie [0 – 100] (100 = parfait)
      > 80  → 0.0   (bon)
      80-60 → 0.0 – 0.40  (normal)
      60-45 → 0.40 – 1.0  (faible, accéléré)
      < 45  → 1.0   (critique)
    """
    if batterie > 80:
        return 0.0
    elif batterie >= 60:
        return clamp((80 - batterie) / 20 * 0.4, 0, 1)
    elif batterie >= 45:
        return clamp(0.4 + (60 - batterie) / 15 * 0.6, 0, 1)
    else:
        return 1.0


def score_heures(heures: float, max_heures: float = 28638) -> float:
    """
    Heures d'utilisation — vieillissement progressif.
    Courbe √ : l'usure accélère avec le temps.
    max_heures = maximum observé dans le dataset (28 638 h).
    """
    return clamp(np.sqrt(heures / max_heures), 0, 1)


def score_historique(pannes: int, anomalies: int) -> float:
    """
    Historique de défaillances (0 ou 1 chacun)
    Pannes pondérées davantage (60%) car plus sérieuses.
    """
    return clamp(0.6 * pannes + 0.4 * anomalies, 0, 1)


# ──────────────────────────────────────────────────────────────────
#  FONCTION PRINCIPALE
# ──────────────────────────────────────────────────────────────────

def calculer_score_predictif(
    temperature_moteur:   float,
    niveaux_vibration:    float,
    qualite_huile:        float,
    etat_freins:          str,
    etat_batterie:        float,
    heures_utilisation:   float,
    historique_pannes:    int,
    anomalies_detectees:  int,
) -> dict:
    """
    Calcule le Score Prédictif de Maintenance d'un véhicule.

    Paramètres
    ----------
    temperature_moteur   : float — Température moteur en °C
    niveaux_vibration    : float — Niveau de vibration (1–12)
    qualite_huile        : float — Qualité de l'huile (0–100)
    etat_freins          : str   — 'bon' | 'moyen' | 'mauvais'
    etat_batterie        : float — État batterie (0–100)
    heures_utilisation   : float — Heures totales d'utilisation
    historique_pannes    : int   — 0 ou 1
    anomalies_detectees  : int   — 0 ou 1

    Retourne
    --------
    dict :
      'score'   : float [0,1]   Score final (0 = sain, 1 = critique)
      'niveau'  : str           'Faible' | 'Modéré' | 'Élevé' | 'Critique'
      'details' : dict          Sous-scores par composant [0,1]
    """

    # ── 1. Sous-scores ──
    details = {
        "temperature" : score_temperature(temperature_moteur),
        "vibration"   : score_vibration(niveaux_vibration),
        "huile"       : score_qualite_huile(qualite_huile),
        "freins"      : score_freins(etat_freins),
        "batterie"    : score_batterie(etat_batterie),
        "heures"      : score_heures(heures_utilisation),
        "historique"  : score_historique(historique_pannes, anomalies_detectees),
    }

    # ── 2. Score brut pondéré ──
    score_brut = sum(POIDS[k] * v for k, v in details.items())

    # ── 3. Power Transform → score final [0,1] ──
    score_final = power_transform(score_brut)

    # ── 4. Niveau de risque ──
    if score_final < 0.30:
        niveau = "Faible"
    elif score_final < 0.55:
        niveau = "Modéré"
    elif score_final < 0.75:
        niveau = "Élevé"
    else:
        niveau = "Critique"

    return {
        "score"  : score_final,
        "niveau" : niveau,
        "details": {k: round(v, 4) for k, v in details.items()},
    }


# ──────────────────────────────────────────────────────────────────
#  CALIBRATION (optionnelle — à relancer si le dataset change)
# ──────────────────────────────────────────────────────────────────

def calibrer_bornes(df: pd.DataFrame) -> tuple[float, float]:
    """
    Recalcule SCORE_BRUT_MIN et SCORE_BRUT_MAX sur un DataFrame.
    À utiliser si le dataset évolue significativement.

    Retourne (min_brut, max_brut) à renseigner dans les constantes.
    """
    scores = []
    for _, row in df.iterrows():
        d = {
            "temperature" : score_temperature(row["Température_Moteur"]),
            "vibration"   : score_vibration(row["Niveaux_Vibration"]),
            "huile"       : score_qualite_huile(row["Qualité_Huile"]),
            "freins"      : score_freins(row["État_Freins"]),
            "batterie"    : score_batterie(row["État_Batterie"]),  # <-- correction ici
            "heures"      : score_heures(row["Heures_Utilisation"]),
            "historique"  : score_historique(row["Historique_Pannes"], row["Anomalies_Détectées"]),
        }
        scores.append(sum(POIDS[k] * v for k, v in d.items()))
    return min(scores), max(scores)


# ──────────────────────────────────────────────────────────────────
#  APPLICATION SUR DATAFRAME
# ──────────────────────────────────────────────────────────────────

def appliquer_sur_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    """
    Applique calculer_score_predictif sur chaque ligne et retourne
    un DataFrame avec les colonnes Score_Prédictif et Niveau_Risque
    mises à jour.
    """
    resultats = df.apply(
        lambda row: calculer_score_predictif(
            temperature_moteur  = row["Température_Moteur"],
            niveaux_vibration   = row["Niveaux_Vibration"],
            qualite_huile       = row["Qualité_Huile"],
            etat_freins         = row["État_Freins"],
            etat_batterie       = row["État_Batterie"],  # <-- correction ici
            heures_utilisation  = row["Heures_Utilisation"],
            historique_pannes   = row["Historique_Pannes"],
            anomalies_detectees = row["Anomalies_Détectées"],
        ),
        axis=1,
        result_type="expand",
    )
    df = df.copy()
    df["Score_Prédictif"] = resultats["score"]
    df["Niveau_Risque"]   = resultats["niveau"]
    return df


# ──────────────────────────────────────────────────────────────────
#  POINT D'ENTRÉE
# ──────────────────────────────────────────────────────────────────

if __name__ == "__main__":

    # ── Test unitaire ──────────────────────────────────────────────
    print("=" * 58)
    print("  TEST UNITAIRE — Véhicule en mauvais état")
    print("=" * 58)

    res = calculer_score_predictif(
        temperature_moteur  = 118.0,
        niveaux_vibration   = 9.5,
        qualite_huile       = 58.0,
        etat_freins         = "mauvais",
        etat_batterie       = 52.0,
        heures_utilisation  = 18000,
        historique_pannes   = 1,
        anomalies_detectees = 1,
    )
    print(f"\n  Score Final   : {res['score']}")
    print(f"  Niveau Risque : {res['niveau']}")
    print("\n  Détail sous-scores :")
    for comp, val in res["details"].items():
        barre = "█" * int(val * 20) + "░" * (20 - int(val * 20))
        print(f"    {comp:<13} [{barre}] {val:.2f}")

    print("\n" + "=" * 58)
    print("  TEST UNITAIRE — Véhicule en bon état")
    print("=" * 58)

    res2 = calculer_score_predictif(
        temperature_moteur  = 92.0,
        niveaux_vibration   = 2.1,
        qualite_huile       = 91.0,
        etat_freins         = "bon",
        etat_batterie       = 88.0,
        heures_utilisation  = 500,
        historique_pannes   = 0,
        anomalies_detectees = 0,
    )
    print(f"\n  Score Final   : {res2['score']}")
    print(f"  Niveau Risque : {res2['niveau']}")

==========================================================
  TEST UNITAIRE — Véhicule en mauvais état
==========================================================

  Score Final   : 1.0
  Niveau Risque : Critique

  Détail sous-scores :
    temperature   [█████████████████░░░] 0.88
    vibration     [██████████████████░░] 0.92
    huile         [█████████████░░░░░░░] 0.68
    freins        [████████████████████] 1.00
    batterie      [██████████████░░░░░░] 0.72
    heures        [███████████████░░░░░] 0.79
    historique    [████████████████████] 1.00

==========================================================
  TEST UNITAIRE — Véhicule en bon état
==========================================================

  Score Final   : 0.0891
  Niveau Risque : Faible

## 6. Génération des Variables Logistiques, Financières et RH

Cette section enrichit le jeu de données avec des variables simulées
nécessaires au module de gestion logistique et financière (Phase 1
du plan de développement TruckMind), en complément des variables
techniques générées à la section 5.

**Variables financières (par véhicule) :**
- Valeur d'achat simulée (MAD)
- Catégorie d'âge (Neuf / Jeune / Moyen / Ancien), basée sur les heures d'utilisation
- Distance totale estimée parcourue (km), dérivée des heures d'utilisation et du type de route
- Coût total de carburant (MAD), basé sur la consommation réelle et un prix de 13,20 MAD/L
- Revenu total estimé (MAD), basé sur le fret transporté (tonnage × distance × tarif de base),
  ajusté par un facteur d'âge du véhicule et par un facteur propre au type de marchandise transportée
- Valeur actuelle (MAD), après dépréciation linéaire sur une durée de vie de 30 000 heures
- Rentabilité nette (MAD) = revenu - coûts (entretien, carburant, dépréciation)

**Variables liées à la marchandise transportée :**
- Type de marchandise (12 catégories : matériaux de construction, produits alimentaires frais,
  produits chimiques, textiles, véhicules et pièces détachées, marchandises générales, produits
  agricoles, électroménager et électronique, produits pharmaceutiques, produits pétroliers,
  bois et matériaux forestiers, métaux et produits sidérurgiques)
- Facteur de tarification associé (marchandises à forte valeur ou sensibles facturées à un
  tarif premium ; marchandises en vrac à faible valeur facturées à un tarif réduit)
- Indicateur de marchandise dangereuse (produits chimiques, produits pétroliers), destiné à
  une utilisation future dans le système de notifications (Phase 3)

**Variables liées au chauffeur :**
- Identifiant, nom complet (données fictives)
- Années d'expérience, salaire de base mensuel
- Numéro et catégorie de permis de conduire, date d'expiration
- Prime d'activité cumulée, liée aux heures d'utilisation du véhicule assigné

**Variables liées au trajet :**
- Nom de l'itinéraire réel (référentiel de routes marocaines)
- Distance et durée estimées de l'itinéraire

*Note méthodologique : l'ensemble de ces variables sont des données simulées
à des fins académiques (absence de télémétrie réelle à ce stade du projet),
construites de manière cohérente entre elles (ex. le coût carburant et le
revenu partagent la même base de calcul : distance parcourue × charge
transportée, avec des facteurs d'ajustement liés à l'âge du véhicule et
au type de marchandise).*

In [30]:
import numpy as np

np.random.seed(44)

# 1. Valeur d'achat
df1['Valeur_Achat_MAD'] = np.random.uniform(900000, 1300000, size=len(df1)).round(0)

# 2. Segmentation par âge
bins   = [0, 1000, 3000, 8000, df1['Heures_Utilisation'].max() + 1]
labels = ['Neuf', 'Jeune', 'Moyen', 'Ancien']
df1['Categorie_Age'] = pd.cut(df1['Heures_Utilisation'], bins=bins, labels=labels, right=False)

taux_horaire = {'Neuf': 320, 'Jeune': 280, 'Moyen': 220, 'Ancien': 160}
df1['Taux_Horaire_Revenu_MAD'] = df1['Categorie_Age'].astype(str).map(taux_horaire)  # ← التصحيح هنا

# 3. Revenu total estimé
df1['Revenu_Total_Estime_MAD'] = df1['Heures_Utilisation'] * df1['Taux_Horaire_Revenu_MAD']

# 4. Dépréciation
DUREE_VIE_HEURES = 30000
df1['Valeur_Actuelle_MAD'] = (
    df1['Valeur_Achat_MAD'] * (1 - df1['Heures_Utilisation'] / DUREE_VIE_HEURES)
).clip(lower=df1['Valeur_Achat_MAD'] * 0.1)

# 5. Rentabilité nette
df1['Rentabilite_Nette_MAD'] = (
    df1['Revenu_Total_Estime_MAD'] - df1['Coût_Entretien']
    - (df1['Valeur_Achat_MAD'] - df1['Valeur_Actuelle_MAD'])
)

print(df1.groupby('Categorie_Age')[['Heures_Utilisation','Revenu_Total_Estime_MAD','Rentabilite_Nette_MAD']].mean())

               Heures_Utilisation  Revenu_Total_Estime_MAD  \
Categorie_Age
Neuf                   470.167304             1.504535e+05
Jeune                 1881.990499             5.269573e+05
Moyen                 4876.269411             1.072779e+06
Ancien               11215.266667             1.794443e+06

               Rentabilite_Nette_MAD
Categorie_Age
Neuf                    1.321673e+05
Jeune                   4.567947e+05
Moyen                   8.930535e+05
Ancien                  1.377337e+06

In [31]:
df1[['Valeur_Achat_MAD','Categorie_Age','Taux_Horaire_Revenu_MAD']].head()

   Valeur_Achat_MAD Categorie_Age  Taux_Horaire_Revenu_MAD
0         1233937.0         Moyen                      220
1          941918.0          Neuf                      320
2         1197856.0         Moyen                      220
3         1044200.0          Neuf                      320
4         1043724.0          Neuf                      320

In [32]:
import numpy as np
import pandas as pd
import itertools

# ============================================================
# 1. VALEUR D'ACHAT DU CAMION (fictive)
# ============================================================
np.random.seed(44)
df1['Valeur_Achat_MAD'] = np.random.uniform(900000, 1300000, size=len(df1)).round(0)

# ============================================================
# 2. SEGMENTATION PAR ÂGE (pour diversité et facteur de tarification)
# ============================================================
bins   = [0, 1000, 3000, 8000, df1['Heures_Utilisation'].max() + 1]
labels = ['Neuf', 'Jeune', 'Moyen', 'Ancien']
df1['Categorie_Age'] = pd.cut(df1['Heures_Utilisation'], bins=bins, labels=labels, right=False)

# ============================================================
# 3. DISTANCE TOTALE ESTIMÉE + COÛT CARBURANT
# ============================================================
PRIX_CARBURANT_MAD_L = 13.20  # prix choisi par l'utilisateur

vitesses_moyennes = {'autoroute': 80, 'urbain': 25, 'rural': 55}  # km/h

df1['Distance_Totale_Estimee_Km'] = (
    df1['Heures_Utilisation'] * df1['Info_Itinéraire'].map(vitesses_moyennes)
)
df1['Carburant_Total_Estime_Litres'] = (
    df1['Distance_Totale_Estimee_Km'] / 100 * df1['Consommation_Carburant']
)
df1['Cout_Carburant_Total_MAD'] = df1['Carburant_Total_Estime_Litres'] * PRIX_CARBURANT_MAD_L

# ============================================================
# 4. REVENU (basé sur distance × charge transportée, cohérent avec le coût carburant)
# ============================================================
PRIX_PAR_TONNE_KM_MAD = 0.5  # tarif de fret (à ajuster si besoin)

facteur_age = {'Neuf': 1.15, 'Jeune': 1.05, 'Moyen': 0.95, 'Ancien': 0.80}
df1['Facteur_Age'] = df1['Categorie_Age'].astype(str).map(facteur_age)

df1['Revenu_Total_Estime_MAD'] = (
    df1['Charge_Réelle'] * df1['Distance_Totale_Estimee_Km']
    * PRIX_PAR_TONNE_KM_MAD * df1['Facteur_Age']
)

# ============================================================
# 5. DÉPRÉCIATION (durée de vie totale = 30 000 heures)
# ============================================================
DUREE_VIE_HEURES = 30000
df1['Valeur_Actuelle_MAD'] = (
    df1['Valeur_Achat_MAD'] * (1 - df1['Heures_Utilisation'] / DUREE_VIE_HEURES)
).clip(lower=df1['Valeur_Achat_MAD'] * 0.1)

# ============================================================
# 6. RENTABILITÉ NETTE
# ============================================================
df1['Rentabilite_Nette_MAD'] = (
    df1['Revenu_Total_Estime_MAD']
    - df1['Coût_Entretien']
    - df1['Cout_Carburant_Total_MAD']
    - (df1['Valeur_Achat_MAD'] - df1['Valeur_Actuelle_MAD'])
)

# ============================================================
# 7. RÉFÉRENTIEL DES CHAUFFEURS (150 chauffeurs uniques)
# ============================================================
np.random.seed(45)

prenoms = ['Youssef','Karim','Mohamed','Hicham','Rachid','Said','Omar','Hamid','Aziz','Khalid',
           'Abdellah','Mustapha','Anas','Younes','Nabil','Tarik','Reda','Adil','Jamal','Mehdi',
           'Yassine','Amine','Soufiane','Hassan','Driss','Zakaria','Othmane','Bilal','Ismail','Fouad']
noms_famille = ['El Amrani','Bennani','Chraibi','Idrissi','Tazi','Fassi','Alaoui','Benjelloun',
                 'Ouazzani','Berrada','Kabbaj','Cherkaoui','Sqalli','Bennis','Ziani','Lahlou',
                 'Mernissi','Sebti','Guessous','Belghazi','Rifai','Skalli','Bouzidi','Naciri',
                 'Zerouali','Hajji','Toumi','Belhaj','Amrani','Sabir']

N_CHAUFFEURS = 150
toutes_combos = list(itertools.product(prenoms, noms_famille))
idx_choisis = np.random.choice(len(toutes_combos), N_CHAUFFEURS, replace=False)
noms_complets = [f"{toutes_combos[i][0]} {toutes_combos[i][1]}" for i in idx_choisis]

chauffeurs_ref = pd.DataFrame({
    'Chauffeur_ID': ['D' + str(i).zfill(3) for i in range(1, N_CHAUFFEURS + 1)],
    'Chauffeur_Nom': noms_complets,
    'Chauffeur_Experience_Annees': np.random.randint(1, 26, size=N_CHAUFFEURS),
    'Permis_Numero': ['PC-' + str(np.random.randint(100000, 999999)) for _ in range(N_CHAUFFEURS)],
    'Permis_Categorie': np.random.choice(['C', 'CE'], size=N_CHAUFFEURS, p=[0.4, 0.6]),
    'Permis_Date_Expiration': pd.to_datetime('2026-07-22') + pd.to_timedelta(
        np.random.randint(-200, 1800, size=N_CHAUFFEURS), unit='D'
    ),
})
chauffeurs_ref['Salaire_Base_Mensuel_MAD'] = 4000 + 150 * chauffeurs_ref['Chauffeur_Experience_Annees']

# ============================================================
# 8. ASSIGNATION D'UN CHAUFFEUR À CHAQUE VÉHICULE
# ============================================================
np.random.seed(46)
df1['Chauffeur_ID'] = np.random.choice(chauffeurs_ref['Chauffeur_ID'], size=len(df1))
df1 = df1.merge(chauffeurs_ref, on='Chauffeur_ID', how='left')

TAUX_PRIME_PAR_HEURE = 0.5  # MAD par heure d'utilisation cumulée
df1['Prime_Activite_MAD'] = df1['Heures_Utilisation'] * TAUX_PRIME_PAR_HEURE

# ============================================================
# 9. ROUTES (référentiel intégré)
# ============================================================
routes_maroc = {
    'autoroute': [
        ('Tanger - Casablanca', 340, 4.0), ('Casablanca - Marrakech', 240, 3.0),
        ('Rabat - Fès', 200, 2.5), ('Casablanca - Agadir', 460, 5.5),
        ('Marrakech - Agadir', 250, 3.2), ('Casablanca - El Jadida', 95, 1.3),
        ('Fès - Oujda', 320, 4.2), ('Tanger - Rabat', 250, 3.0),
    ],
    'urbain': [
        ('Casablanca - Centre Ville', 15, 1.0), ('Tanger - Zone Industrielle', 10, 0.8),
        ('Rabat - Salé', 12, 0.9), ('Marrakech - Menara', 8, 0.6),
        ('Fès - Ville Nouvelle', 14, 1.1), ('Agadir - Centre', 11, 0.9),
    ],
    'rural': [
        ('Essaouira - Chichaoua', 90, 2.0), ('Taza - Oujda', 220, 4.0),
        ('Béni Mellal - Azilal', 85, 2.2), ('Ouarzazate - Zagora', 165, 3.5),
        ('Chefchaouen - Ouezzane', 60, 1.8), ('Sefrou - Boulemane', 70, 2.0),
    ],
}
np.random.seed(47)

def choisir_route(type_route):
    options = routes_maroc[type_route]
    return options[np.random.randint(len(options))]

resultats = df1['Info_Itinéraire'].apply(choisir_route)
df1['Route_Nom']             = resultats.apply(lambda x: x[0])
df1['Route_Distance_Km']     = resultats.apply(lambda x: x[1])
df1['Route_Duree_Estimee_H'] = resultats.apply(lambda x: x[2])

# ============================================================
# 10. VÉRIFICATION FINALE
# ============================================================
print(f'Nombre de chauffeurs uniques utilisés : {df1["Chauffeur_ID"].nunique()} / {N_CHAUFFEURS}')
print(f'Nombre de noms uniques : {df1["Chauffeur_Nom"].nunique()}')
print(f'Nombre de routes uniques : {df1["Route_Nom"].nunique()}')
print()

Nombre de chauffeurs uniques utilisés : 150 / 150
Nombre de noms uniques : 150
Nombre de routes uniques : 20

In [33]:
df1[['Identifiant_Véhicule','Categorie_Age','Revenu_Total_Estime_MAD',
           'Cout_Carburant_Total_MAD','Rentabilite_Nette_MAD',
           'Chauffeur_Nom','Salaire_Base_Mensuel_MAD','Route_Nom']].head(8)

,Identifiant_Véhicule,Categorie_Age,Revenu_Total_Estime_MAD,Cout_Carburant_Total_MAD,Rentabilite_Nette_MAD,Chauffeur_Nom,Salaire_Base_Mensuel_MAD,Route_Nom
0,V0001,Moyen,3.487795e+06,1946894.40,1.388295e+06,Adil Bouzidi,5200,Tanger - Rabat
1,V0002,Neuf,8.654777e+04,19430.40,6.266596e+04,Abdellah Bennis,5800,Casablanca - Centre Ville
2,V0003,Moyen,6.293975e+06,3704923.20,2.333874e+06,Anas Chraibi,7300,Tanger - Casablanca
3,V0004,Neuf,1.301225e+04,6911.52,4.284500e+03,Hassan El Amrani,7000,Marrakech - Menara
4,V0005,Neuf,2.551667e+05,149497.92,8.922752e+04,Rachid Ouazzani,6250,Essaouira - Chichaoua
5,V0006,Ancien,7.704238e+06,3498475.20,3.875741e+06,Karim El Amrani,4750,Tanger - Rabat
6,V0007,Neuf,1.664862e+05,89231.67,5.847026e+04,Hamid Ziani,6250,Marrakech - Menara
7,V0008,Neuf,3.012178e+05,157669.05,1.281249e+05,Mustapha Belghazi,5350,Essaouira - Chichaoua

In [34]:
print()
print('% de véhicules rentables :', (df1['Rentabilite_Nette_MAD'] > 0).mean() * 100)
print(df1['Rentabilite_Nette_MAD'].describe())

% de véhicules rentables : 98.97733554449972
count    3.618000e+03
mean     1.060653e+06
std      1.469342e+06
min     -1.018897e+06
25%      2.320890e+05
50%      5.808904e+05
75%      1.308872e+06
max      2.150251e+07
Name: Rentabilite_Nette_MAD, dtype: float64

In [35]:
np.random.seed(48)

types_marchandise = [
    'Matériaux de construction', 'Produits alimentaires (frais)', 'Produits chimiques',
    'Textiles', 'Véhicules et pièces détachées', 'Marchandises générales',
    'Produits agricoles', 'Électroménager et électronique', 'Produits pharmaceutiques',
    'Produits pétroliers', 'Bois et matériaux forestiers', 'Métaux et produits sidérurgiques',
]

# Fréquence approximative sur le marché marocain (bulk/générique domine)
probabilites = [0.16, 0.14, 0.07, 0.09, 0.08, 0.13, 0.10, 0.04, 0.03, 0.06, 0.05, 0.05]

# Facteur de tarification par type (1.00 = tarif de base)
# > 1.00 : marchandise à valeur ajoutée / sensible / urgente → tarif premium
# < 1.00 : marchandise en vrac, faible valeur au volume → tarif réduit
facteurs_marchandise = {
    'Matériaux de construction':        0.90,
    'Produits alimentaires (frais)':    1.20,  # chaîne du froid, délais courts
    'Produits chimiques':               1.35,  # manutention spécialisée, risque
    'Textiles':                         1.00,
    'Véhicules et pièces détachées':    1.15,  # forte valeur, soin requis
    'Marchandises générales':           1.00,
    'Produits agricoles':               0.85,  # vrac, faible valeur/tonne
    'Électroménager et électronique':   1.25,  # forte valeur, fragile
    'Produits pharmaceutiques':         1.50,  # réglementé, chaîne du froid stricte
    'Produits pétroliers':              1.30,  # danger, transport réglementé
    'Bois et matériaux forestiers':     0.80,  # vrac, faible valeur
    'Métaux et produits sidérurgiques': 0.95,
}

df1['Type_Marchandise']   = np.random.choice(types_marchandise, size=len(df1), p=probabilites)
df1['Facteur_Marchandise'] = df1['Type_Marchandise'].map(facteurs_marchandise)

# Indicateur de marchandise dangereuse (utile pour Phase 3 - notifications prioritaires)
marchandises_dangereuses = ['Produits chimiques', 'Produits pétroliers']
df1['Marchandise_Dangereuse'] = df1['Type_Marchandise'].isin(marchandises_dangereuses)

# --- Mise à jour du Revenu pour inclure le facteur marchandise ---
df1['Revenu_Total_Estime_MAD'] = (
    df1['Charge_Réelle'] * df1['Distance_Totale_Estimee_Km']
    * PRIX_PAR_TONNE_KM_MAD * df1['Facteur_Age'] * df1['Facteur_Marchandise']
)

# --- Recalcul de la rentabilité avec le nouveau revenu ---
df1['Rentabilite_Nette_MAD'] = (
    df1['Revenu_Total_Estime_MAD']
    - df1['Coût_Entretien']
    - df1['Cout_Carburant_Total_MAD']
    - (df1['Valeur_Achat_MAD'] - df1['Valeur_Actuelle_MAD'])
)

print(df1['Type_Marchandise'].value_counts())
print()
print('% rentable :', (df1['Rentabilite_Nette_MAD'] > 0).mean() * 100)
print(df1.groupby('Type_Marchandise')['Rentabilite_Nette_MAD'].mean().sort_values(ascending=False))

Type_Marchandise
Matériaux de construction           576
Produits alimentaires (frais)       500
Marchandises générales              450
Produits agricoles                  366
Textiles                            348
Véhicules et pièces détachées       295
Produits chimiques                  246
Produits pétroliers                 232
Bois et matériaux forestiers        181
Métaux et produits sidérurgiques    173
Électroménager et électronique      142
Produits pharmaceutiques            109
Name: count, dtype: int64

% rentable : 98.47982310668878

Type_Marchandise
Produits pharmaceutiques            2.442748e+06
Produits chimiques                  1.888405e+06
Électroménager et électronique      1.654946e+06
Produits pétroliers                 1.649791e+06
Produits alimentaires (frais)       1.524101e+06
Véhicules et pièces détachées       1.417923e+06
Marchandises générales              1.234573e+06
Textiles                            9.619168e+05
Métaux et produits sidérurgiques    8.293779e+05
Produits agricoles                  8.160411e+05
Matériaux de construction           7.578834e+05
Bois et matériaux forestiers        4.892952e+05
Name: Rentabilite_Nette_MAD, dtype: float64

## 7. Vérification Finale et Export

Contrôle visuel du DataFrame nettoyé avant export au format CSV.

In [36]:
#---- Suppression des colonnes inutiles ---
df1.drop(columns=['Taux_Horaire_Revenu_MAD', 'Facteur_Age'], inplace=True)

In [37]:
# --- Export du DataFrame nettoyé au format CSV ---
# Le fichier résultant servira de base au système RAG.

import os
script_dir = os.path.dirname(os.path.abspath("__file__"))
project_root = os.path.dirname(script_dir)
OUTPUT_CSV = os.path.join(project_root, "uploads", "truckmind_dataset_complet.csv")
df1.to_csv(OUTPUT_CSV, index=False)
print(f'Jeu de données exporté : {OUTPUT_CSV} ({len(df1)} lignes, {len(df1.columns)} colonnes)')

Jeu de données exporté : e:\1er_projet_de_maitenance_predicitive\uploads\truckmind_dataset_complet.csv (3618 lignes, 47 colonnes)

In [38]:
# --- Aperçu des 15 premières observations du DataFrame nettoyé ---
df1.head(15)

,Identifiant_Véhicule,Année_Fabrication,Heures_Utilisation,Info_Itinéraire,Capacité_Charge,Charge_Réelle,Date_Dernier_Entretien,Type_Entretien,Coût_Entretien,Température_Moteur,...,Permis_Categorie,Permis_Date_Expiration,Salaire_Base_Mensuel_MAD,Prime_Activite_MAD,Route_Nom,Route_Distance_Km,Route_Duree_Estimee_H,Type_Marchandise,Facteur_Marchandise,Marchandise_Dangereuse
0,V0001,2020,3615,autoroute,23.745401,25.389787,2023-07-09,révision du moteur,3916.151008,117.1,...,C,2028-12-21,5200,1807.5,Tanger - Rabat,250,3.0,Matériaux de construction,0.90,False
1,V0002,2021,128,urbain,41.784895,47.036831,2023-02-03,rotation des pneus,432.556669,103.9,...,C,2029-09-28,5800,64.0,Casablanca - Centre Ville,15,1.0,Produits pétroliers,1.30,True
2,V0003,2016,6379,autoroute,29.507143,25.965031,2023-04-08,changement d'huile,474.508408,112.1,...,C,2028-07-22,7300,3189.5,Tanger - Casablanca,340,4.0,Produits alimentaires (frais),1.20,False
3,V0004,2005,44,urbain,27.319939,20.572720,2023-03-13,rotation des pneus,284.732675,97.9,...,CE,2031-01-27,7000,22.0,Marrakech - Menara,8,0.6,Produits alimentaires (frais),1.20,False
4,V0005,2014,468,rural,21.902258,17.240408,2023-05-09,changement d'huile,159.129571,119.3,...,CE,2026-05-11,6250,234.0,Essaouira - Chichaoua,90,2.0,Électroménager et électronique,1.25,False
5,V0006,2022,8650,autoroute,25.986585,27.833230,2023-03-04,changement d'huile,256.385524,102.2,...,C,2026-04-05,4750,4325.0,Tanger - Rabat,250,3.0,Produits chimiques,1.35,True
6,V0007,2020,521,urbain,20.693001,22.229658,2023-01-03,changement d'huile,418.853826,102.8,...,CE,2029-04-01,6250,260.5,Marrakech - Menara,8,0.6,Produits pétroliers,1.30,True
7,V0008,2013,425,rural,21.560186,22.410997,2023-12-11,changement d'huile,355.727330,108.4,...,CE,2031-02-02,5350,212.5,Essaouira - Chichaoua,90,2.0,Textiles,1.00,False
8,V0009,2021,3772,autoroute,41.770024,45.594913,2023-06-26,changement d'huile,499.832682,94.7,...,CE,2026-06-19,4450,1886.0,Tanger - Rabat,250,3.0,Marchandises générales,1.00,False
9,V0010,2018,7223,rural,24.729445,17.352147,2023-12-26,changement d'huile,272.587849,103.6,...,CE,2026-12-08,5800,3611.5,Sefrou - Boulemane,70,2.0,Produits chimiques,1.35,True
10,V0011,2020,473,autoroute,29.357184,27.827661,2023-05-19,changement d'huile,352.831847,110.3,...,CE,2026-07-08,7750,236.5,Casablanca - Marrakech,240,3.0,Matériaux de construction,0.90,False
11,V0012,2018,374,urbain,26.369083,24.809834,2024-01-05,révision du moteur,2348.398458,94.4,...,CE,2029-01-17,6100,187.0,Rabat - Salé,12,0.9,Matériaux de construction,0.90,False
12,V0013,2005,2683,rural,21.559945,22.002193,2023-06-12,rotation des pneus,370.498533,113.5,...,C,2030-09-26,6400,1341.5,Béni Mellal - Azilal,85,2.2,Textiles,1.00,False
13,V0014,2022,871,autoroute,20.580836,20.464926,2023-10-30,changement d'huile,380.512495,116.7,...,CE,2029-05-03,7750,435.5,Rabat - Fès,200,2.5,Produits agricoles,0.85,False
14,V0015,2014,9675,urbain,28.661761,24.502528,2023-03-25,changement d'huile,347.577172,96.2,...,C,2028-02-19,5200,4837.5,Marrakech - Menara,8,0.6,Véhicules et pièces détachées,1.15,False

In [39]:
# --- Statistiques descriptives des variables catégorielles ---
df1.describe(include='object')

,Identifiant_Véhicule,Info_Itinéraire,Type_Entretien,État_Freins,Conditions_Météo,Conditions_Route,Chauffeur_ID,Chauffeur_Nom,Permis_Numero,Permis_Categorie,Route_Nom,Type_Marchandise
count,3618,3618,3618,3618,3618,3618,3618,3618,3618,3618,3618,3618
unique,3618,3,3,3,4,3,150,150,150,2,20,12
top,V0001,autoroute,changement d'huile,bon,clair,autoroute,D028,Younes Guessous,PC-324882,CE,Fès - Oujda,Matériaux de construction
freq,1,1825,1660,1824,2926,1421,38,38,38,2087,248,576

In [40]:
# --- Statistiques descriptives des variables numériques (float) ---
df1.describe(include='float64')

,Capacité_Charge,Charge_Réelle,Coût_Entretien,Température_Moteur,Pression_Pneus,Consommation_Carburant,État_Batterie,Niveaux_Vibration,Qualité_Huile,Score_Prédictif,...,Impact_Efficacité,Valeur_Achat_MAD,Revenu_Total_Estime_MAD,Valeur_Actuelle_MAD,Rentabilite_Nette_MAD,Carburant_Total_Estime_Litres,Cout_Carburant_Total_MAD,Prime_Activite_MAD,Route_Duree_Estimee_H,Facteur_Marchandise
count,3618.000000,3618.000000,3618.000000,3618.000000,3618.000000,3618.000000,3618.000000,3618.000000,3618.000000,3618.000000,...,3618.000000,3.618000e+03,3.618000e+03,3.618000e+03,3.618000e+03,3.618000e+03,3.618000e+03,3618.000000,3618.000000,3618.000000
mean,28.314610,26.799877,1020.555969,105.413184,118.003870,46.470951,77.176009,7.049627,79.439685,0.168084,...,0.209092,1.101643e+06,2.430397e+06,9.921123e+05,1.212399e+06,8.389745e+04,1.107446e+06,1488.826009,2.543532,1.064290
std,7.689804,8.334987,1553.867511,9.062776,7.333331,5.690425,10.282673,2.602135,9.806641,0.100688,...,0.111409,1.149148e+05,2.898887e+06,1.517466e+05,1.780739e+06,9.962887e+04,1.315101e+06,1518.587514,1.359960,0.182517
min,20.010818,14.229736,100.223731,78.300000,92.800000,31.800000,45.100000,1.050000,43.176358,0.001042,...,0.100000,9.000590e+05,0.000000e+00,1.130467e+05,-1.492892e+06,0.000000e+00,0.000000e+00,0.000000,0.600000,0.800000
25%,23.042691,21.006162,229.508521,98.900000,114.000000,42.200000,70.000000,5.110000,72.927933,0.091810,...,0.105212,1.004868e+06,6.107179e+05,8.972912e+05,2.313546e+05,1.963521e+04,2.591848e+05,417.500000,1.300000,0.900000
50%,26.334410,24.959597,349.593575,105.400000,119.200000,46.700000,77.500000,6.935000,79.346645,0.149336,...,0.179810,1.099772e+06,1.511329e+06,9.932044e+05,6.214041e+05,5.040079e+04,6.652904e+05,1001.250000,2.500000,1.000000
75%,29.554764,30.240114,471.906150,111.900000,123.500000,51.000000,84.500000,8.950000,86.193171,0.228324,...,0.272367,1.202359e+06,3.085547e+06,1.102800e+06,1.481662e+06,1.113964e+05,1.470433e+06,2090.000000,3.500000,1.200000
max,54.965729,65.029212,5999.042959,128.000000,132.100000,55.000000,100.000000,12.000000,100.000000,0.665510,...,0.741097,1.299705e+06,4.300749e+07,1.297876e+06,3.029144e+07,1.152393e+06,1.521159e+07,14319.000000,5.500000,1.500000

In [41]:
# --- Export du DataFrame nettoyé au format CSV ---
# Le fichier résultant servira de base au système RAG.

OUTPUT_CSV = r'E:\1er_projet_de_maitenance_predicitive\uploads\truckmind_dataset_complet.csv'
df1.to_csv(OUTPUT_CSV, index=False)
print(f'Exporté : {OUTPUT_CSV} ({len(df1)} lignes, {len(df1.columns)} colonnes)')

Exporté : E:\1er_projet_de_maitenance_predicitive\uploads\truckmind_dataset_complet.csv (3618 lignes, 47 colonnes)