# Projet de Stage Technique - EST (DUT)
## Nettoyage et Préparation du Jeu de Données de Maintenance des Camions

---

**Objectif :**  
Ce notebook présente les étapes de nettoyage, de standardisation et d'enrichissement
du jeu de données de maintenance de la flotte de camions Volvo FH.
Le résultat final est un fichier CSV exploitable par un système de maintenance prédictive basé sur l'IA.

**Plan du notebook :**
1. Importation des bibliothèques et chargement des données
2. Renommage des colonnes
3. Exploration et analyse initiale
4. Nettoyage des données (doublons, valeurs nulles, aberrantes)
5. Filtrage et sélection du sous-ensemble d'étude
6. Standardisation des variables catégorielles
7. Génération des variables manquantes (simulation réaliste)
8. Export CSV et génération du rapport PDF

---

In [1]:
# =============================================================
# Projet de Stage Technique - EST (DUT)
# Module : Traitement et Nettoyage des Données
# Fichier : Nettoyage du jeu de données de maintenance des camions
# =============================================================

# --- Importation des bibliothèques nécessaires ---
import os
import itertools
import random

import numpy as np
import pandas as pd

warnings_off = True
import warnings
warnings.filterwarnings('ignore')

print('Bibliothèques importées avec succès.')

# 0. CONFIGURATION

CSV_INPUT = 'logistics_dataset_with_maintenance_required.csv'

N_VEHICULES = 1000          # nombre de véhicules physiques uniques
MIN_TRAJETS_PAR_VEHICULE = 1
PRIX_CARBURANT_MAD_L = 13.20
PRIX_PAR_TONNE_KM_MAD = 0.5
DUREE_VIE_HEURES = 30000
TAUX_PRIME_PAR_HEURE = 0.5
ANNEE_REFERENCE = 2026      # pour le calcul de la catégorie d'âge du véhicule
 
SEED_BASE = 44

# --- Chargement du jeu de données brut ---
df = pd.read_csv(CSV_INPUT, delimiter=';')
print(f'Données chargées : {df.shape[0]} lignes, {df.shape[1]} colonnes.')

Bibliothèques importées avec succès.
Données chargées : 92000 lignes, 27 colonnes.

In [2]:
# --- Renommage des colonnes (anglais -> français) ---
# Objectif : uniformiser les noms de colonnes en français
# pour faciliter la lecture et l'interprétation des données.

new_columns = {
    'Vehicle_ID'          : 'Identifiant_Véhicule',
    'Make_and_Model'      : 'Marque_et_Modèle',
    'Year_of_Manufacture' : 'Année_Fabrication',
    'Vehicle_Type'        : 'Type_Véhicule',
    'Usage_Hours'         : 'Heures_Utilisation',
    'Route_Info'          : 'Info_Itinéraire',
    'Load_Capacity'       : 'Capacité_Charge',
    'Actual_Load'         : 'Charge_Réelle',
    'Last_Maintenance_Date': 'Date_Dernier_Entretien',
    'Maintenance_Type'    : 'Type_Entretien',
    'Maintenance_Cost'    : 'Coût_Entretien',
    'Engine_Temperature'  : 'Température_Moteur',
    'Tire_Pressure'       : 'Pression_Pneus',
    'Fuel_Consumption'    : 'Consommation_Carburant',
    'Battery_Status'      : 'État_Batterie',
    'Vibration_Levels'    : 'Niveaux_Vibration',
    'Oil_Quality'         : 'Qualité_Huile',
    'Brake_Condition'     : 'État_Freins',
    'Failure_History'     : 'Historique_Pannes',
    'Anomalies_Detected'  : 'Anomalies_Détectées',
    'Predictive_Score'    : 'Score_Prédictif',
    'Maintenance_Required': 'Entretien_Nécessaire',
    'Weather_Conditions'  : 'Conditions_Météo',
    'Road_Conditions'     : 'Conditions_Route',
    'Delivery_Times'      : 'Délais_Livraison',
    'Downtime_Maintenance': 'Temps_Arrêt_Entretien',
    'Impact_on_Efficiency': 'Impact_Efficacité',
}

df.rename(columns=new_columns, inplace=True)
print('Colonnes renommées avec succès.')

Colonnes renommées avec succès.

## 2. Exploration Initiale des Données

Avant tout traitement, il est indispensable d'examiner la structure du DataFrame :
types de données, présence de valeurs nulles, et statistiques descriptives.

In [3]:
# --- Aperçu des 5 premières lignes du DataFrame ---
df.head()

,Identifiant_Véhicule,Marque_et_Modèle,Année_Fabrication,Type_Véhicule,Heures_Utilisation,Info_Itinéraire,Capacité_Charge,Charge_Réelle,Date_Dernier_Entretien,Type_Entretien,...,État_Freins,Historique_Pannes,Anomalies_Détectées,Score_Prédictif,Entretien_Nécessaire,Conditions_Météo,Conditions_Route,Délais_Livraison,Temps_Arrêt_Entretien,Impact_Efficacité
0,1,Ford F-150,2022,Truck,530,Rural,7.534549,9.004247,09/04/2023,Oil Change,...,Good,1,0,0.171873,1,Clear,Highway,30.000000,0.093585,0.150063
1,2,Volvo FH,2015,Van,10679,Rural,7.671728,6.111785,20/07/2023,Tire Rotation,...,Fair,1,0,0.246670,1,Clear,Rural,30.000000,3.361201,0.343017
2,3,Chevy Silverado,2022,Van,4181,Rural,2.901159,3.006055,17/03/2023,Oil Change,...,Good,1,1,0.455236,1,Clear,Highway,48.627823,1.365300,0.100000
3,4,Chevy Silverado,2011,Truck,2974,Urban,15.893347,18.825290,01/05/2024,Tire Rotation,...,Good,0,1,0.060208,1,Clear,Highway,30.000000,0.000000,0.135749
4,5,Ford F-150,2014,Van,2539,Rural,60.668320,65.605463,15/11/2023,Tire Rotation,...,Good,1,1,0.264929,1,Rainy,Urban,300.000000,6.608704,0.395193

In [4]:
# --- Informations générales sur le DataFrame ---
print('=== Informations sur les colonnes et les types de données ===')
df.info()

# --- Statistiques descriptives globales ---
print('\n=== Statistiques descriptives ===')
df.describe(include='all')

=== Informations sur les colonnes et les types de données ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92000 entries, 0 to 91999
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Identifiant_Véhicule    92000 non-null  int64
 1   Marque_et_Modèle        92000 non-null  object
 2   Année_Fabrication       92000 non-null  int64
 3   Type_Véhicule           92000 non-null  object
 4   Heures_Utilisation      92000 non-null  int64
 5   Info_Itinéraire         92000 non-null  object
 6   Capacité_Charge         92000 non-null  float64
 7   Charge_Réelle           92000 non-null  float64
 8   Date_Dernier_Entretien  92000 non-null  object
 9   Type_Entretien          92000 non-null  object
 10  Coût_Entretien          92000 non-null  float64
 11  Température_Moteur      92000 non-null  float64
 12  Pression_Pneus          92000 non-null  float64
 13  Consommation_Carburant  92000 non-null  float64
 14  État_Batterie           92000 non-null  float64
 15  Niveaux_Vibration       92000 non-null  float64
 16  Qualité_Huile           92000 non-null  float64
 17  État_Freins             92000 non-null  object
 18  Historique_Pannes       92000 non-null  int64
 19  Anomalies_Détectées     92000 non-null  int64
 20  Score_Prédictif         92000 non-null  float64
 21  Entretien_Nécessaire    92000 non-null  int64
 22  Conditions_Météo        92000 non-null  object
 23  Conditions_Route        92000 non-null  object
 24  Délais_Livraison        92000 non-null  float64
 25  Temps_Arrêt_Entretien   92000 non-null  float64
 26  Impact_Efficacité       92000 non-null  float64
dtypes: float64(13), int64(6), object(8)
memory usage: 19.0+ MB

=== Statistiques descriptives ===

,Identifiant_Véhicule,Marque_et_Modèle,Année_Fabrication,Type_Véhicule,Heures_Utilisation,Info_Itinéraire,Capacité_Charge,Charge_Réelle,Date_Dernier_Entretien,Type_Entretien,...,État_Freins,Historique_Pannes,Anomalies_Détectées,Score_Prédictif,Entretien_Nécessaire,Conditions_Météo,Conditions_Route,Délais_Livraison,Temps_Arrêt_Entretien,Impact_Efficacité
count,92000.00000,92000,92000.000000,92000,92000.000000,92000,92000.000000,92000.000000,92000,92000,...,92000,92000.000000,92000.000000,92000.000000,92000.000000,92000,92000,92000.000000,92000.000000,92000.000000
unique,NaN,4,NaN,2,NaN,3,NaN,NaN,547,3,...,3,NaN,NaN,NaN,NaN,4,3,NaN,NaN,NaN
top,NaN,Ford F-150,NaN,Van,NaN,Highway,NaN,NaN,26/03/2023,Oil Change,...,Good,NaN,NaN,NaN,NaN,Clear,Highway,NaN,NaN,NaN
freq,NaN,45917,NaN,50850,NaN,46052,NaN,NaN,219,41488,...,45938,NaN,NaN,NaN,NaN,73482,36861,NaN,NaN,NaN
mean,46000.50000,NaN,2016.968478,NaN,2989.550913,NaN,25.068001,23.771355,NaN,NaN,...,NaN,0.399565,0.452196,0.166754,0.767989,NaN,NaN,99.283161,3.210282,0.208325
std,26558.25672,NaN,5.359597,NaN,2992.083426,NaN,25.040153,24.194555,NaN,NaN,...,NaN,0.489812,0.497712,0.103435,0.422118,NaN,NaN,79.708201,6.429751,0.111234
min,1.00000,NaN,2005.000000,NaN,0.000000,NaN,0.000013,0.000010,NaN,NaN,...,NaN,0.000000,0.000000,0.000161,0.000000,NaN,NaN,30.000000,0.000000,0.100000
25%,23000.75000,NaN,2013.000000,NaN,856.000000,NaN,7.233425,6.725843,NaN,NaN,...,NaN,0.000000,0.000000,0.087777,1.000000,NaN,NaN,30.000000,0.000000,0.106637
50%,46000.50000,NaN,2020.000000,NaN,2070.000000,NaN,17.401696,16.245317,NaN,NaN,...,NaN,0.000000,0.000000,0.147868,1.000000,NaN,NaN,69.617815,0.000000,0.179359
75%,69000.25000,NaN,2021.000000,NaN,4146.000000,NaN,34.746243,32.681695,NaN,NaN,...,NaN,1.000000,1.000000,0.227352,1.000000,NaN,NaN,139.084008,3.775145,0.271323
max,92000.00000,NaN,2022.000000,NaN,36392.000000,NaN,332.341562,264.033718,NaN,NaN,...,NaN,1.000000,1.000000,0.746450,1.000000,NaN,NaN,300.000000,88.624732,0.822859

In [5]:
# --- Vérification des types de données par colonne ---
print('Types de données par colonne :')
print(df.dtypes)

Types de données par colonne :
Identifiant_Véhicule        int64
Marque_et_Modèle           object
Année_Fabrication           int64
Type_Véhicule              object
Heures_Utilisation          int64
Info_Itinéraire            object
Capacité_Charge           float64
Charge_Réelle             float64
Date_Dernier_Entretien     object
Type_Entretien             object
Coût_Entretien            float64
Température_Moteur        float64
Pression_Pneus            float64
Consommation_Carburant    float64
État_Batterie             float64
Niveaux_Vibration         float64
Qualité_Huile             float64
État_Freins                object
Historique_Pannes           int64
Anomalies_Détectées         int64
Score_Prédictif           float64
Entretien_Nécessaire        int64
Conditions_Météo           object
Conditions_Route           object
Délais_Livraison          float64
Temps_Arrêt_Entretien     float64
Impact_Efficacité         float64
dtype: object

In [6]:
# --- Détection des valeurs manquantes ---
# Étape essentielle avant tout traitement pour identifier
# les colonnes nécessitant une imputation ou une suppression.
print('Nombre de valeurs nulles par colonne :')
print(df.isnull().sum())

Nombre de valeurs nulles par colonne :
Identifiant_Véhicule      0
Marque_et_Modèle          0
Année_Fabrication         0
Type_Véhicule             0
Heures_Utilisation        0
Info_Itinéraire           0
Capacité_Charge           0
Charge_Réelle             0
Date_Dernier_Entretien    0
Type_Entretien            0
Coût_Entretien            0
Température_Moteur        0
Pression_Pneus            0
Consommation_Carburant    0
État_Batterie             0
Niveaux_Vibration         0
Qualité_Huile             0
État_Freins               0
Historique_Pannes         0
Anomalies_Détectées       0
Score_Prédictif           0
Entretien_Nécessaire      0
Conditions_Météo          0
Conditions_Route          0
Délais_Livraison          0
Temps_Arrêt_Entretien     0
Impact_Efficacité         0
dtype: int64

## 3. Nettoyage des Données

Cette section couvre la suppression des doublons, le filtrage du périmètre d'étude
et le traitement des valeurs aberrantes (outliers).

In [17]:
# --- Suppression des lignes dupliquées ---
# Les doublons peuvent fausser les analyses et les modèles.
nb_avant = len(df)
df = df.drop_duplicates()
nb_apres = len(df)
print(f'{nb_avant - nb_apres} ligne(s) dupliquée(s) supprimée(s).')
print(f'Nombre de lignes restantes : {nb_apres}')

0 ligne(s) dupliquée(s) supprimée(s).
Nombre de lignes restantes : 92000

In [18]:
# --- Filtrage : sélection du modèle Volvo FH de type Camion ---
# Le périmètre d'étude se limite au modèle Volvo FH (Truck)
# afin d'obtenir un jeu de données homogène.

df1 = df[(df['Marque_et_Modèle'] == 'Volvo FH') & (df['Type_Véhicule'] == 'Truck')].copy()
df1.reset_index(drop=True, inplace=True)
df1['Identifiant_Véhicule'] = range(1, len(df1) + 1)

print(f'Nombre de lignes après filtrage : {len(df1)}')
df1[['Identifiant_Véhicule', 'Marque_et_Modèle', 'Type_Véhicule']].head()

Nombre de lignes après filtrage : 4092

   Identifiant_Véhicule Marque_et_Modèle Type_Véhicule
0                     1         Volvo FH         Truck
1                     2         Volvo FH         Truck
2                     3         Volvo FH         Truck
3                     4         Volvo FH         Truck
4                     5         Volvo FH         Truck

In [19]:
# --- Suppression des colonnes non pertinentes pour l'analyse ---
# Les colonnes suivantes sont hors périmètre ou redondantes :
# Marque_et_Modèle, Type_Véhicule, Délais_Livraison,
# Temps_Arrêt_Entretien, Impact_Efficacité, Coût_Entretien.

colonnes_a_supprimer = [
    'Marque_et_Modèle', 'Type_Véhicule']
    
df1.drop(colonnes_a_supprimer, axis=1, inplace=True)
print(f'Colonnes conservées : {list(df1.columns)}')
df1.head()

Colonnes conservées : ['Identifiant_Véhicule', 'Année_Fabrication', 'Heures_Utilisation', 'Info_Itinéraire', 'Capacité_Charge', 'Charge_Réelle', 'Date_Dernier_Entretien', 'Type_Entretien', 'Coût_Entretien', 'Température_Moteur', 'Pression_Pneus', 'Consommation_Carburant', 'État_Batterie', 'Niveaux_Vibration', 'Qualité_Huile', 'État_Freins', 'Historique_Pannes', 'Anomalies_Détectées', 'Score_Prédictif', 'Entretien_Nécessaire', 'Conditions_Météo', 'Conditions_Route', 'Délais_Livraison', 'Temps_Arrêt_Entretien', 'Impact_Efficacité']

,Identifiant_Véhicule,Année_Fabrication,Heures_Utilisation,Info_Itinéraire,Capacité_Charge,Charge_Réelle,Date_Dernier_Entretien,Type_Entretien,Coût_Entretien,Température_Moteur,...,État_Freins,Historique_Pannes,Anomalies_Détectées,Score_Prédictif,Entretien_Nécessaire,Conditions_Météo,Conditions_Route,Délais_Livraison,Temps_Arrêt_Entretien,Impact_Efficacité
0,1,2020,4506,Highway,62.037153,45.324843,15/05/2024,Oil Change,233.178588,120.0,...,Fair,0,0,0.199099,0,Clear,Highway,44.975126,0.000000,0.329284
1,2,2020,3615,Highway,5.969894,6.383313,09/07/2023,Engine Overhaul,3916.151008,120.0,...,Good,0,1,0.149013,1,Clear,Urban,110.286110,0.000000,0.105513
2,3,2021,128,Urban,41.784895,47.036831,03/02/2023,Tire Rotation,432.556669,120.0,...,Poor,0,0,0.251046,1,Clear,Rural,30.000000,0.000000,0.105065
3,4,2016,6379,Highway,2.909616,2.560338,08/04/2023,Oil Change,474.508408,120.0,...,Good,1,1,0.117144,1,Clear,Rural,147.207972,1.010687,0.100000
4,5,2005,44,Urban,8.864533,6.675255,13/03/2023,Tire Rotation,284.732675,120.0,...,Poor,1,0,0.469806,1,Clear,Urban,33.441818,6.650673,0.100000

In [20]:
# --- Analyse statistique de la variable Capacité_Charge ---
# Permet d'identifier les valeurs aberrantes ou incohérentes.

print('=== Statistiques descriptives de Capacité_Charge ===')
print(df1['Capacité_Charge'].describe())

=== Statistiques descriptives de Capacité_Charge ===
count    4092.000000
mean       25.495392
std        25.688815
min         0.017976
25%         7.333189
50%        17.736672
75%        35.350269
max       255.985201
Name: Capacité_Charge, dtype: float64

In [21]:
# --- Détection d'une valeur suspecte dans Capacité_Charge ---
# Vérification si une valeur précise (ex. 255.985201) est sur-représentée,
# ce qui pourrait indiquer une erreur de saisie ou de génération.

valeur_cible = 255.985201
tolerance = 1e-6

nb_exact  = (df1['Capacité_Charge'] == valeur_cible).sum()
nb_approx = ((df1['Capacité_Charge'] - valeur_cible).abs() < tolerance).sum()

print(f'Correspondances exactes  : {nb_exact}')
print(f'Correspondances (tol={tolerance}) : {nb_approx}')

lignes_trouvees = df1[(df1['Capacité_Charge'] - valeur_cible).abs() < tolerance]
print('\nAperçu des lignes concernées :')
print(lignes_trouvees[['Capacité_Charge']].head())

Correspondances exactes  : 0
Correspondances (tol=1e-06) : 1

Aperçu des lignes concernées :
     Capacité_Charge
633       255.985201

In [22]:
# --- Identification des valeurs hors plage réaliste ---
# Un camion Volvo FH a une capacité maximale standard d'environ 26 à 30 tonnes.
# Toute valeur largement supérieure est considérée comme aberrante.

nb_capacite = (df1['Capacité_Charge'] > 50).sum()
nb_charge   = (df1['Charge_Réelle']   > 60).sum()

print(f'Lignes avec Capacité_Charge > 50 tonnes : {nb_capacite}')
print(f'Lignes avec Charge_Réelle   > 60 tonnes : {nb_charge}')

Lignes avec Capacité_Charge > 50 tonnes : 581
Lignes avec Charge_Réelle   > 60 tonnes : 346

In [23]:
# --- Suppression des observations aberrantes (Capacité_Charge > 55 tonnes) ---
# Seules les lignes dont la capacité de charge est réaliste sont conservées.

df1 = df1[df1['Capacité_Charge'] <= 55].copy()
df1.reset_index(drop=True, inplace=True)
df1['Identifiant_Véhicule'] = range(1, len(df1) + 1)

print(f'Nombre de lignes après filtrage : {len(df1)}')
print('\nVérification des premières lignes :')
print(df1[['Identifiant_Véhicule', 'Capacité_Charge']].head())
print('\nVérification des dernières lignes :')
print(df1[['Identifiant_Véhicule', 'Capacité_Charge']].tail())

Nombre de lignes après filtrage : 3618

Vérification des premières lignes :
   Identifiant_Véhicule  Capacité_Charge
0                     1         5.969894
1                     2        41.784895
2                     3         2.909616
3                     4         8.864533
4                     5        21.902258

Vérification des dernières lignes :
      Identifiant_Véhicule  Capacité_Charge
3613                  3614        48.206528
3614                  3615        22.463914
3615                  3616         8.239716
3616                  3617         7.371252
3617                  3618        16.798042

In [24]:
# --- Vérification de la variable Charge_Réelle après nettoyage ---

nb_charge = (df1['Charge_Réelle'] > 55).sum()
print(f'Nombre de lignes avec Charge_Réelle > 55 tonnes : {nb_charge}')

Nombre de lignes avec Charge_Réelle > 55 tonnes : 34

In [25]:
print("=== PARTIE 1 : ANALYSE DES VALEURS ORIGINALES (DÉCIMALES) < 20 ===")

# 1. Filtrer les valeurs strictement inférieures à 20 (sans conversion)
valeurs_moins_de_20 = df1[df1['Capacité_Charge'] < 20]

# 2. Filtrer pour ne conserver que les nombres qui sont déjà des entiers mathématiques (ex: 17.0)
valeurs_entieres_naturelles = valeurs_moins_de_20[
    valeurs_moins_de_20['Capacité_Charge'].apply(lambda x: x.is_integer())
]

print(f"Nombre total d'enregistrements < 20 (origine) : {len(valeurs_moins_de_20)}")
print(f"Nombre d'enregistrements avec des entiers purs (ex: 17.0) : {len(valeurs_entieres_naturelles)}")

if len(valeurs_entieres_naturelles) > 0:
    uniques_entiers_purs = sorted(valeurs_entieres_naturelles['Capacité_Charge'].unique())
    print(f"Valeurs UNIQUES entières (sans conversion) : {uniques_entiers_purs}")
else:
    print("Aucune valeur entière pure trouvée.")

# -------------------------------------------------------------------
# NOUVELLE PARTIE : CONVERSION DE TOUTES LES VALEURS EN ENTIERS,
# PUIS AFFICHAGE DES VALEURS UNIQUES < 20
# -------------------------------------------------------------------
print("\n=== PARTIE 2 : CONVERSION DE TOUTES LES VALEURS EN ENTIERS (ARRONDIS) ===")

# 1. Convertir la colonne ENTIÈRE en nombres entiers (arrondi mathématique)
#    Exemple : 7.33 -> 7, 17.73 -> 18, 25.49 -> 25
valeurs_arrondies = df1['Capacité_Charge'].round(0).astype(int)

# 2. Filtrer ces entiers convertis pour ne garder que ceux < 20
entiers_convertis_moins_20 = valeurs_arrondies[valeurs_arrondies < 20]

# 3. Extraire les VALEURS UNIQUES (c'est-à-dire les entiers distincts) et les trier
uniques_entiers_converties = sorted(entiers_convertis_moins_20.unique())

# 4. Afficher les résultats
print(f"Nombre total d'enregistrements (après conversion) < 20 : {len(entiers_convertis_moins_20)}")
print(f"VALEURS UNIQUES (entiers arrondis) inférieures à 20 : {uniques_entiers_converties}")

# (Optionnel) Afficher le détail du comptage par valeur unique
print("\nDétail du comptage pour chaque valeur unique :")
for val in uniques_entiers_converties:
    count = (entiers_convertis_moins_20 == val).sum()
    print(f"   - {val} tonne(s) : {count} occurrences")

# -------------------------------------------------------------------
# PETITE COMPARAISON POUR VOUS AIDER À INTERPRÉTER
# -------------------------------------------------------------------
print("\n=== COMPARAISON ENTRE LES DEUX MÉTHODES ===")
print(f"Nombre de valeurs UNIQUES < 20 sans conversion : {len(valeurs_entieres_naturelles['Capacité_Charge'].unique()) if len(valeurs_entieres_naturelles)>0 else 0}")
print(f"Nombre de valeurs UNIQUES < 20 après conversion : {len(uniques_entiers_converties)}")

=== PARTIE 1 : ANALYSE DES VALEURS ORIGINALES (DÉCIMALES) < 20 ===
Nombre total d'enregistrements < 20 (origine) : 2235
Nombre d'enregistrements avec des entiers purs (ex: 17.0) : 0
Aucune valeur entière pure trouvée.

=== PARTIE 2 : CONVERSION DE TOUTES LES VALEURS EN ENTIERS (ARRONDIS) ===
Nombre total d'enregistrements (après conversion) < 20 : 2193
VALEURS UNIQUES (entiers arrondis) inférieures à 20 : [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19)]

Détail du comptage pour chaque valeur unique :
   - 0 tonne(s) : 77 occurrences
   - 1 tonne(s) : 169 occurrences
   - 2 tonne(s) : 146 occurrences
   - 3 tonne(s) : 140 occurrences
   - 4 tonne(s) : 130 occurrences
   - 5 tonne(s) : 138 occurrences
   - 6 tonne(s) : 126 occurrences
   - 7 tonne(s) : 126 occurrences
   - 8 tonne(s) : 97 occurrences
   - 9 tonne(s) : 86 occurrences
   - 10 tonne(s) : 109 occurrences
   - 11 tonne(s) : 121 occurrences
   - 12 tonne(s) : 110 occurrences
   - 13 tonne(s) : 98 occurrences
   - 14 tonne(s) : 77 occurrences
   - 15 tonne(s) : 113 occurrences
   - 16 tonne(s) : 87 occurrences
   - 17 tonne(s) : 78 occurrences
   - 18 tonne(s) : 92 occurrences
   - 19 tonne(s) : 73 occurrences

=== COMPARAISON ENTRE LES DEUX MÉTHODES ===
Nombre de valeurs UNIQUES < 20 sans conversion : 0
Nombre de valeurs UNIQUES < 20 après conversion : 20

In [26]:
import numpy as np
np.random.seed(42)

masque_irrealiste = df1['Capacité_Charge'] < 20
n_corrige = masque_irrealiste.sum()

# 1. Sauvegarder le ratio d'utilisation original AVANT toute modification
#    (Charge_Réelle a été générée comme un % de Capacité_Charge, entre ~0.70 et 1.20)
ratio_utilisation = (
    df1.loc[masque_irrealiste, 'Charge_Réelle'] / df1.loc[masque_irrealiste, 'Capacité_Charge']
)

# 2. Générer une nouvelle Capacité_Charge réaliste (20 à 30 tonnes)
df1.loc[masque_irrealiste, 'Capacité_Charge'] = np.random.uniform(20, 30, size=n_corrige)

# 3. Recalculer Charge_Réelle en appliquant le MÊME ratio à la nouvelle capacité
#    → préserve exactement la logique de génération originale du dataset
df1.loc[masque_irrealiste, 'Charge_Réelle'] = (
    ratio_utilisation.values * df1.loc[masque_irrealiste, 'Capacité_Charge']
)

print(f'{n_corrige} lignes corrigées sur {len(df1)} ({n_corrige/len(df1)*100:.1f}%)')
print()
print('Capacité_Charge après correction :')
print(df1['Capacité_Charge'].describe())
print()
print('Charge_Réelle après correction :')
print(df1['Charge_Réelle'].describe())
print()
print('Vérification — ratio Charge_Réelle/Capacité_Charge global (doit rester ~0.70-1.20) :')
print((df1['Charge_Réelle']/df1['Capacité_Charge']).describe())

2235 lignes corrigées sur 3618 (61.8%)

Capacité_Charge après correction :
count    3618.000000
mean       28.314610
std         7.689804
min        20.010818
25%        23.042691
50%        26.334410
75%        29.554764
max        54.965729
Name: Capacité_Charge, dtype: float64

Charge_Réelle après correction :
count    3618.000000
mean       26.799877
std         8.334987
min        14.229736
25%        21.006162
50%        24.959597
75%        30.240114
max        65.029212
Name: Charge_Réelle, dtype: float64

Vérification — ratio Charge_Réelle/Capacité_Charge global (doit rester ~0.70-1.20) :
count    3618.000000
mean        0.946943
std         0.144007
min         0.700246
25%         0.821643
50%         0.947544
75%         1.072133
max         1.199882
dtype: float64

## 4. Standardisation des Variables Catégorielles

Traduction des modalités anglaises en français et normalisation de la casse
pour garantir la cohérence du jeu de données.

In [27]:
# --- Traduction des valeurs textuelles (anglais -> français) ---
# Standardisation des modalités pour les variables catégorielles.

df1['Info_Itinéraire'] = df1['Info_Itinéraire'].replace({
    'Rural'  : 'rural',
    'Highway': 'autoroute',
    'Urban'  : 'urbain'
})

df1['Conditions_Route'] = df1['Conditions_Route'].replace({
    'Rural'  : 'rural',
    'Highway': 'autoroute',
    'Urban'  : 'urbain'
})

df1['Type_Entretien'] = df1['Type_Entretien'].replace({
    'Engine Overhaul': 'révision du moteur',
    'Oil Change'     : "changement d'huile",
    'Tire Rotation'  : 'rotation des pneus',
})

df1['Conditions_Météo'] = df1['Conditions_Météo'].replace({
    'Clear' : 'clair',
    'Rainy' : 'pluvieux',
    'Snowy' : 'neigeux',
    'Windy' : 'venteux'
})

df1['État_Freins'] = df1['État_Freins'].replace({
    'Good': 'bon',
    'Fair': 'moyen',
    'Poor': 'mauvais'
})

# Vérification des valeurs uniques après traduction
for col in ['Info_Itinéraire', 'Conditions_Route',
            'Type_Entretien', 'Conditions_Météo', 
            'État_Freins']:
    print(f'{col} : {df1[col].unique()}')

Info_Itinéraire : ['autoroute' 'urbain' 'rural']
Conditions_Route : ['urbain' 'rural' 'autoroute']
Type_Entretien : ['révision du moteur' 'rotation des pneus' "changement d'huile"]
Conditions_Météo : ['clair' 'pluvieux' 'venteux' 'neigeux']
État_Freins : ['bon' 'mauvais' 'moyen']

In [28]:
# --- Normalisation des chaînes de caractères (mise en minuscules) ---
# Garantit l'uniformité des modalités textuelles
# et évite les incohérences dues à la casse.

colonnes_texte = df1.select_dtypes(include=['object']).columns
df1[colonnes_texte] = df1[colonnes_texte].apply(lambda x: x.str.lower())

print('Aperçu des colonnes textuelles après normalisation :')
df1[colonnes_texte].head()

Aperçu des colonnes textuelles après normalisation :

,Info_Itinéraire,Date_Dernier_Entretien,Type_Entretien,État_Freins,Conditions_Météo,Conditions_Route
0,autoroute,09/07/2023,révision du moteur,bon,clair,urbain
1,urbain,03/02/2023,rotation des pneus,mauvais,clair,rural
2,autoroute,08/04/2023,changement d'huile,bon,clair,rural
3,urbain,13/03/2023,rotation des pneus,mauvais,clair,urbain
4,rural,09/05/2023,changement d'huile,bon,clair,autoroute

In [29]:
# --- Conversion de la colonne de date en type datetime ---
# Nécessaire pour tout calcul ou filtrage temporel ultérieur.

df1['Date_Dernier_Entretien'] = pd.to_datetime(
    df1['Date_Dernier_Entretien'], format='%d/%m/%Y', errors='coerce'
)
print(df1['Date_Dernier_Entretien'].isnull().sum())

0

In [30]:
# --- Vérification de la cohérence entre Conditions_Route et Info_Itinéraire ---
# Ces deux colonnes devraient contenir les mêmes informations.
# Un écart signifie une incohérence dans la source de données.

comparaison = df1['Conditions_Route'] == df1['Info_Itinéraire']
nb_differences = (~comparaison).sum()

print(f'Nombre de lignes divergentes : {nb_differences}')
if nb_differences > 0:
    print('Exemples de divergences :')
    print(df1[~comparaison][['Conditions_Route', 'Info_Itinéraire']].head())
else:
    print('Les deux colonnes sont parfaitement identiques sur tout le jeu de données.')

print(f'Taux de concordance : {comparaison.mean() * 100:.2f}%')

Nombre de lignes divergentes : 2345
Exemples de divergences :
  Conditions_Route Info_Itinéraire
0           urbain       autoroute
1            rural          urbain
2            rural       autoroute
4        autoroute           rural
6            rural          urbain
Taux de concordance : 35.19%

In [31]:
# =====================================================================
# 7. ★ NOUVEAU ★ — SÉPARATION VÉHICULE (fixe) / TRAJET (variable)
# =====================================================================
#
# Idée : df1 contient actuellement ~3618 lignes issues du fichier brut.
# On les traite désormais comme des ENREGISTREMENTS DE TRAJET, et on les
# répartit entre 1000 véhicules physiques distincts.
#
# Étape A — construire le référentiel des 1000 véhicules (attributs fixes)
# Étape B — répartir les lignes de df1 (trajets) entre ces 1000 véhicules
# Étape C — recalculer Charge_Réelle en cohérence avec la Capacité_Charge
#           réellement assignée au véhicule (préserve le ratio d'origine)
# Étape D — trier Heures_Utilisation de façon croissante dans le temps,
#           par véhicule (réalisme : l'usure augmente avec les trajets)
# =====================================================================

n_trajets = len(df1)
assert n_trajets >= N_VEHICULES, "Pas assez de lignes pour couvrir 1000 véhicules distincts."

# --- Étape A : référentiel véhicules (attributs FIXES) ---------------
np.random.seed(SEED_BASE)
idx_profils_vehicules = np.random.choice(df1.index, size=N_VEHICULES, replace=False)

vehicules_ref = df1.loc[idx_profils_vehicules, ['Année_Fabrication', 'Capacité_Charge']].copy()
vehicules_ref.reset_index(drop=True, inplace=True)
vehicules_ref['Identifiant_Véhicule'] = ['V' + str(i).zfill(4) for i in range(1, N_VEHICULES + 1)]

# Valeur d'achat : générée UNE SEULE FOIS par véhicule
np.random.seed(SEED_BASE)
vehicules_ref['Valeur_Achat_MAD'] = np.random.uniform(900000, 1300000, size=N_VEHICULES).round(0)

# Catégorie d'âge : basée sur l'Année_Fabrication (attribut du véhicule),
# plus logique qu'une base sur les Heures_Utilisation (qui varie par trajet)
def categorie_age_vehicule(annee):
    age = ANNEE_REFERENCE - annee
    if age <= 2:
        return 'Neuf'
    elif age <= 5:
        return 'Jeune'
    elif age <= 10:
        return 'Moyen'
    else:
        return 'Ancien'

vehicules_ref['Categorie_Age'] = vehicules_ref['Année_Fabrication'].apply(categorie_age_vehicule)

facteur_age = {'Neuf': 1.15, 'Jeune': 1.05, 'Moyen': 0.95, 'Ancien': 0.80}
vehicules_ref['Facteur_Age'] = vehicules_ref['Categorie_Age'].map(facteur_age)

print('\nRépartition des véhicules par catégorie d\'âge :')
print(vehicules_ref['Categorie_Age'].value_counts())

# --- Étape B : préparation du pool de trajets + assignation véhicule --
trajets = df1.drop(columns=['Année_Fabrication', 'Capacité_Charge']).copy()
trajets.reset_index(drop=True, inplace=True)

# Sauvegarde du ratio d'utilisation d'origine (Charge_Réelle / Capacité_Charge)
# calculé AVANT réassignation, pour préserver la logique métier du trajet.
ratio_charge_original = (
    df1.loc[trajets.index, 'Charge_Réelle'] / df1.loc[trajets.index, 'Capacité_Charge']
)
trajets['__ratio_charge__'] = ratio_charge_original.values

# Assignation : chaque véhicule reçoit AU MOINS 1 trajet (garanti),
# puis les trajets restants sont répartis aléatoirement.
np.random.seed(SEED_BASE + 1)
ordre_trajets = np.random.permutation(n_trajets)

assignation = np.empty(n_trajets, dtype=object)
# 1er passage : chaque véhicule reçoit un trajet garanti
assignation[ordre_trajets[:N_VEHICULES]] = vehicules_ref['Identifiant_Véhicule'].values
# 2e passage : trajets restants répartis aléatoirement entre les 1000 véhicules
n_restants = n_trajets - N_VEHICULES
assignation[ordre_trajets[N_VEHICULES:]] = np.random.choice(
    vehicules_ref['Identifiant_Véhicule'].values, size=n_restants, replace=True
)

trajets['Identifiant_Véhicule'] = assignation

# --- Étape C : jointure avec le référentiel véhicule + recalcul Charge_Réelle
trajets = trajets.merge(
    vehicules_ref[['Identifiant_Véhicule', 'Année_Fabrication', 'Capacité_Charge',
                    'Valeur_Achat_MAD', 'Categorie_Age', 'Facteur_Age']],
    on='Identifiant_Véhicule', how='left'
)

# Charge_Réelle recalculée pour rester cohérente avec la Capacité_Charge
# RÉELLEMENT assignée au véhicule (le trajet peut avoir été tiré d'une
# ligne brute différente ayant une autre capacité d'origine).
trajets['Charge_Réelle'] = trajets['__ratio_charge__'] * trajets['Capacité_Charge']
trajets.drop(columns=['__ratio_charge__'], inplace=True)

# --- Étape D : Heures_Utilisation croissante dans le temps par véhicule
# Pour chaque véhicule : on classe ses trajets par date (croissante) et on
# leur affecte les valeurs d'Heures_Utilisation de ce même véhicule,
# elles aussi triées par ordre croissant. Résultat : les heures cumulées
# augmentent avec la chronologie des trajets du véhicule.
# (Implémentation vectorisée avec tri + cumcount, sans groupby.apply,
#  pour rester compatible avec toutes les versions de pandas.)

trajets = trajets.reset_index(drop=True)

# 1) position de chaque trajet dans l'ordre chronologique (par véhicule)
ordre_par_date = trajets.sort_values(['Identifiant_Véhicule', 'Date_Dernier_Entretien'],
                                      na_position='last')
pos_date = ordre_par_date.groupby('Identifiant_Véhicule').cumcount()
trajets['__pos_date__'] = pos_date  # aligné par index -> pas de perte de colonnes

# 2) valeurs d'Heures_Utilisation du véhicule, triées par ordre croissant
ordre_par_heures = trajets.sort_values(['Identifiant_Véhicule', 'Heures_Utilisation'])
pos_heures = ordre_par_heures.groupby('Identifiant_Véhicule').cumcount()
ordre_par_heures = ordre_par_heures.assign(__pos_heures__=pos_heures.values)

# 3) table de correspondance (véhicule, position) -> valeur d'heures triée
correspondance = ordre_par_heures.set_index(['Identifiant_Véhicule', '__pos_heures__'])['Heures_Utilisation']

# 4) on réaffecte : pour chaque trajet, on prend la valeur triée
#    correspondant à sa position chronologique
cle = list(zip(trajets['Identifiant_Véhicule'], trajets['__pos_date__']))
trajets['Heures_Utilisation'] = correspondance.loc[cle].values

trajets.drop(columns=['__pos_date__'], inplace=True)

# Identifiant unique de TRAJET (remplace l'ancien rôle de Identifiant_Véhicule
# comme clé de ligne — désormais Identifiant_Véhicule peut se répéter)
trajets = trajets.sample(frac=1, random_state=SEED_BASE + 2).reset_index(drop=True)  # mélange final
trajets['Trajet_ID'] = ['T' + str(i).zfill(5) for i in range(1, len(trajets) + 1)]

df1 = trajets  # à partir d'ici, df1 = table des TRAJETS (niveau ligne)

print(f'\nNombre de trajets générés : {len(df1)}')
print(f'Nombre de véhicules distincts utilisés : {df1["Identifiant_Véhicule"].nunique()} / {N_VEHICULES}')
print('Nombre de trajets par véhicule — statistiques :')
print(df1['Identifiant_Véhicule'].value_counts().describe())

Répartition des véhicules par catégorie d'âge :
Categorie_Age
Jeune     377
Ancien    320
Moyen     303
Name: count, dtype: int64

Nombre de trajets générés : 3618
Nombre de véhicules distincts utilisés : 1000 / 1000
Nombre de trajets par véhicule — statistiques :
count    1000.000000
mean        3.618000
std         1.608933
min         1.000000
25%         2.000000
50%         3.000000
75%         5.000000
max        10.000000
Name: count, dtype: float64

In [32]:
df1.head()

,Identifiant_Véhicule,Heures_Utilisation,Info_Itinéraire,Charge_Réelle,Date_Dernier_Entretien,Type_Entretien,Coût_Entretien,Température_Moteur,Pression_Pneus,Consommation_Carburant,...,Conditions_Route,Délais_Livraison,Temps_Arrêt_Entretien,Impact_Efficacité,Année_Fabrication,Capacité_Charge,Valeur_Achat_MAD,Categorie_Age,Facteur_Age,Trajet_ID
0,V0979,1524,autoroute,24.294535,2023-01-31,changement d'huile,101.871845,120.0,55.000000,20.000000,...,rural,30.000000,0.000000,0.253143,2011,27.553428,1042289.0,Ancien,0.80,T00001
1,V0729,1078,rural,28.847604,2023-10-30,changement d'huile,403.881135,120.0,20.000000,5.000000,...,rural,82.131821,0.171344,0.300555,2012,25.014646,1229799.0,Ancien,0.80,T00002
2,V0737,516,autoroute,20.019576,2024-01-17,changement d'huile,310.528505,120.0,35.470258,5.000000,...,rural,118.489921,8.351760,0.284760,2020,22.156752,1047854.0,Moyen,0.95,T00003
3,V0244,1640,urbain,19.915936,2023-05-09,rotation des pneus,208.685345,120.0,39.375149,15.051568,...,autoroute,30.000000,0.000000,0.100000,2022,26.340057,960256.0,Jeune,1.05,T00004
4,V0444,5304,autoroute,21.923719,2024-01-19,rotation des pneus,327.980516,120.0,20.000000,20.000000,...,autoroute,30.000000,0.000000,0.335705,2010,26.070940,1245725.0,Ancien,0.80,T00005

## 5. Génération Synthétique des Variables Capteurs (niveau TRAJET)

Les variables suivantes sont recalculées à partir de modèles paramétriques
basés sur les caractéristiques physiques du camion Volvo FH :
- Température moteur (°C)
- Pression des pneus (kPa)
- Consommation carburant (L/100 km)
- Etat de la batterie (%)
- Niveaux de vibration

---

!! Logique inchangée — s'applique maintenant sur la table trajets, avec Capacité_Charge/Charge_Réelle correctement cohérentes

In [33]:
# ─────────────────────────────────────────────────────────────────
# Génération synthétique de la variable Température_Moteur
# Modèle basé sur : surcharge, anomalies, pannes, météo,
#                   conditions routières, heures d'utilisation.
# Plage réaliste pour un Volvo FH : 75 à 128 °C
# ─────────────────────────────────────────────────────────────────

def generer_temperature_moteur(ligne):
    temperature = random.uniform(82, 96)
    overload_ratio = ligne['Charge_Réelle'] / ligne['Capacité_Charge']
    if overload_ratio > 1:
        temperature += min((overload_ratio - 1) * 25, 18)
    if ligne['Anomalies_Détectées'] == 1:
        temperature += random.uniform(8, 16)
    if ligne['Historique_Pannes'] == 1:
        temperature += random.uniform(3, 7)
    if ligne['Conditions_Météo'] == 'pluvieux':
        temperature -= random.uniform(2, 4)
    elif ligne['Conditions_Météo'] == 'clair':
        temperature += random.uniform(4, 6)
    elif ligne['Conditions_Météo'] == 'neigeux':
        temperature -= random.uniform(3, 6)
    if ligne['Conditions_Route'] == 'urbain':
        temperature += random.uniform(2, 5)
    elif ligne['Conditions_Route'] == 'autoroute':
        temperature += random.uniform(5, 10)
    temperature += min(ligne['Heures_Utilisation'] / 5000, 9)
    temperature += random.uniform(-1.5, 1.5)
    return round(min(max(temperature, 75), 128), 1)

print('bien passe')

bien passe

In [34]:
# ─────────────────────────────────────────────────────────────────
# Génération synthétique de la variable Pression_Pneus
# Modèle basé sur : surcharge, météo, anomalies, heures d'utilisation.
# Plage réaliste pour un camion lourd : 85 à 140 kPa
# ─────────────────────────────────────────────────────────────────

def generer_pression_pneus(ligne):
    pression = random.uniform(112, 125)
    overload_ratio = ligne['Charge_Réelle'] / ligne['Capacité_Charge']
    if overload_ratio > 1:
        pression += min((overload_ratio - 1) * 10, 8)
    if ligne['Conditions_Météo'] == 'clair':
        pression += random.uniform(2, 5)
    elif ligne['Conditions_Météo'] == 'neigeux':
        pression -= random.uniform(1, 3)
    if ligne['Anomalies_Détectées'] == 1 and random.random() < 0.6:
        pression -= random.uniform(8, 18)
    pression -= min(ligne['Heures_Utilisation'] / 10000, 4)
    pression += random.uniform(-1.5, 1.5)
    return round(min(max(pression, 85), 140), 1)

print("bien passe")

bien passe

In [35]:
# ─────────────────────────────────────────────────────────────────
# Génération synthétique de la variable Consommation_Carburant
# Modèle basé sur : charge, type de route, météo,
#                   historique de pannes, heures d'utilisation.
# Plage réaliste : 24 à 55 L/100 km
# ─────────────────────────────────────────────────────────────────

def generer_consommation_carburant(ligne):
    consommation = random.uniform(29, 36)
    overload_ratio = ligne['Charge_Réelle'] / ligne['Capacité_Charge']
    consommation += min(overload_ratio * 6, 12)
    route = ligne['Conditions_Route']
    if route == 'urbain':
        consommation += random.uniform(3, 6)
    elif route == 'rural':
        consommation += random.uniform(5, 10)
    elif route == 'autoroute':
        consommation -= random.uniform(1, 3)
    meteo = ligne['Conditions_Météo']
    if meteo == 'neigeux':
        consommation += random.uniform(2, 5)
    elif meteo == 'pluvieux':
        consommation += random.uniform(1, 3)
    elif meteo == 'clair':
        consommation += random.uniform(0.5, 1.5)
    if ligne['Historique_Pannes'] == 1:
        consommation += random.uniform(2, 5)
    consommation += min(ligne['Heures_Utilisation'] / 7000, 6)
    if ligne['Anomalies_Détectées'] == 1:
        consommation += random.uniform(3, 8)
    consommation += random.uniform(-1.5, 1.5)
    return round(min(max(consommation, 24), 55), 1)

print("bien passe")

bien passe

In [36]:
# ─────────────────────────────────────────────────────────────────
# Génération synthétique de la variable Etat_Batterie
# Modèle basé sur : heures d'utilisation, pannes, anomalies,
#                   météo et conditions routières.
# Plage réaliste : 15 à 100 %
# ─────────────────────────────────────────────────────────────────

def generer_etat_batterie(ligne):
    batterie = random.uniform(80, 100)
    batterie -= min(ligne['Heures_Utilisation'] / 2500, 35)
    if ligne['Historique_Pannes'] == 1:
        batterie -= random.uniform(5, 12)
    if ligne['Anomalies_Détectées'] == 1:
        batterie -= random.uniform(8, 18)
    meteo = ligne['Conditions_Météo']
    if meteo == 'neigeux':
        batterie -= random.uniform(4, 8)
    elif meteo == 'pluvieux':
        batterie -= random.uniform(2, 5)
    elif meteo == 'venteux':
        batterie -= random.uniform(1, 3)
    route = ligne['Conditions_Route']
    if route == 'urbain':
        batterie -= random.uniform(2, 5)
    elif route == 'rural':
        batterie -= random.uniform(1, 3)
    batterie += random.uniform(-2, 2)
    return round(min(max(batterie, 15), 100), 1)

print("bien passe")

bien passe

In [37]:
# ─────────────────────────────────────────────────────────────────
# Génération synthétique de la variable Niveaux_Vibration
# Modèle basé sur : usure mécanique, anomalies, pannes,
#                   état des freins, qualité de l'huile,
#                   conditions routières et météo.
# Plage réaliste : 1 à 12 (unité arbitraire de vibration)
# ─────────────────────────────────────────────────────────────────

def generer_niveaux_vibration(ligne):
    vibration = random.uniform(1.8, 4.2)
    vibration += min(ligne['Heures_Utilisation'] / 9000, 4)
    if ligne['Anomalies_Détectées'] == 1:
        vibration += random.uniform(2, 5)
    if ligne['Historique_Pannes'] == 1:
        vibration += random.uniform(1, 3)
    if str(ligne['État_Freins']).lower() in ['mauvais', 'critique', 'usé']:
        vibration += random.uniform(1.5, 3.5)
    if float(ligne['Qualité_Huile']) < 40:
        vibration += random.uniform(1, 3)
    route = ligne['Conditions_Route']
    if route == 'urbain':
        vibration += random.uniform(0.5, 1.5)
    elif route == 'rural':
        vibration += random.uniform(1, 2)
    elif route == 'autoroute':
        vibration -= random.uniform(0.2, 0.8)
    meteo = ligne['Conditions_Météo']
    if meteo == 'neigeux':
        vibration += random.uniform(0.5, 1.5)
    elif meteo == 'venteux':
        vibration += random.uniform(0.3, 1)
    vibration += random.uniform(-0.3, 0.3)
    return round(min(max(vibration, 1), 12), 2)

print ("bien passe")

bien passe

In [38]:
random.seed(SEED_BASE + 3)
df1['Température_Moteur']     = df1.apply(generer_temperature_moteur, axis=1)
df1['Pression_Pneus']         = df1.apply(generer_pression_pneus, axis=1)
df1['Consommation_Carburant'] = df1.apply(generer_consommation_carburant, axis=1)
df1['État_Batterie']          = df1.apply(generer_etat_batterie, axis=1)
df1['Niveaux_Vibration']      = df1.apply(generer_niveaux_vibration, axis=1)

print('\nVariables capteurs générées (Température, Pression, Consommation, Batterie, Vibration).')

Variables capteurs générées (Température, Pression, Consommation, Batterie, Vibration).

In [39]:
"""
    ====================================================================
    Score Prédictif de Maintenance — Fonction de calcul raisonnée
    ====================================================================

    LOGIQUE GÉNÉRALE
    ----------------
    Le score final est calculé en 3 étapes :

    1. Calcul de 7 sous-scores partiels, chacun sur [0, 1]
    (0 = parfait état, 1 = état critique)

    2. Agrégation pondérée → score brut sur [0, 1]

    3. Mise à l'échelle par Power Transform (exposant 0.5)
    après Min-Max sur les bornes réelles observées.
    Cela étale le score sur tout [0, 1] sans déformer
    le classement, et pénalise davantage les cas extrêmes.

    POURQUOI PAS LA SIGMOÏDE ?
    ---------------------------
    La sigmoïde compresse les queues et laisse le 75e centile
    autour de 0.42. Le Power Transform (racine carrée) étale
    naturellement les valeurs basses tout en conservant les
    valeurs hautes proches de 1. Résultat :
    - 75e centile ≈ 0.72   ✓
    - Cas critique → proche de 1.0  ✓
    - Cas sain     → proche de 0.0  ✓

    SOUS-SCORES ET POIDS
    ---------------------
    Composant              Poids   Justification
    ---------------------  ------  -----------------------------------------
    Température moteur      0.20   Surchauffe → dommages immédiats
    État freins             0.20   Sécurité critique
    Niveaux vibration       0.15   Indique usure mécanique
    Qualité huile           0.15   Lubrifiant dégradé → pannes moteur
    État batterie           0.10   Alimentation électronique
    Heures utilisation      0.10   Vieillissement progressif (courbe √)
    Anomalies + Pannes      0.10   Historique de défaillances
    ---------------------  ------  -----------------------------------------
    TOTAL                   1.00

    BORNES DE NORMALISATION (calibrées sur le dataset réel)
    ---------------------------------------------------------
    SCORE_BRUT_MIN = 0.0064   (meilleur véhicule observé)
    SCORE_BRUT_MAX = 0.8647   (pire véhicule observé)

    Ces valeurs peuvent être recalibrées via calibrer_bornes()
    si le dataset évolue.

    SEUILS DE RISQUE (score final)
    --------------------------------
    [0.00 – 0.30[  →  Faible
    [0.30 – 0.55[  →  Modéré
    [0.55 – 0.75[  →  Élevé
    [0.75 – 1.00]  →  Critique
    ====================================================================
"""

import pandas as pd
import numpy as np


POIDS = {"temperature": 0.20, "freins": 0.20, "vibration": 0.15, "huile": 0.15,
         "batterie": 0.10, "heures": 0.10, "historique": 0.10}
SCORE_BRUT_MIN, SCORE_BRUT_MAX, POWER_EXPOSANT = 0.0064, 0.8647, 0.5


def clamp(v, lo, hi):
    return max(lo, min(hi, v))


def power_transform(score_brut):
    n = clamp((score_brut - SCORE_BRUT_MIN) / (SCORE_BRUT_MAX - SCORE_BRUT_MIN), 0.0, 1.0)
    return round(n ** POWER_EXPOSANT, 4)


def score_temperature(t):
    if t < 95: return 0.0
    if t <= 110: return clamp((t - 95) / 15 * 0.4, 0, 1)
    if t <= 120: return clamp(0.4 + (t - 110) / 10 * 0.6, 0, 1)
    return 1.0


def score_vibration(v):
    if v < 3: return 0.0
    if v <= 7: return clamp((v - 3) / 4 * 0.5, 0, 1)
    if v <= 10: return clamp(0.5 + (v - 7) / 3 * 0.5, 0, 1)
    return 1.0


def score_qualite_huile(q):
    if q > 85: return 0.0
    if q >= 65: return clamp((85 - q) / 20 * 0.4, 0, 1)
    if q >= 50: return clamp(0.4 + (65 - q) / 15 * 0.6, 0, 1)
    return 1.0


def score_freins(e):
    return {"bon": 0.0, "moyen": 0.5, "mauvais": 1.0}.get(str(e).strip().lower(), 0.5)


def score_batterie(b):
    if b > 80: return 0.0
    if b >= 60: return clamp((80 - b) / 20 * 0.4, 0, 1)
    if b >= 45: return clamp(0.4 + (60 - b) / 15 * 0.6, 0, 1)
    return 1.0


def score_heures(h, max_h=28638):
    return clamp(np.sqrt(h / max_h), 0, 1)


def score_historique(p, a):
    return clamp(0.6 * p + 0.4 * a, 0, 1)


def calculer_score_predictif(row):
    details = {
        "temperature": score_temperature(row['Température_Moteur']),
        "vibration"  : score_vibration(row['Niveaux_Vibration']),
        "huile"      : score_qualite_huile(row['Qualité_Huile']),
        "freins"     : score_freins(row['État_Freins']),
        "batterie"   : score_batterie(row['État_Batterie']),
        "heures"     : score_heures(row['Heures_Utilisation']),
        "historique" : score_historique(row['Historique_Pannes'], row['Anomalies_Détectées']),
    }
    score_brut = sum(POIDS[k] * v for k, v in details.items())
    score_final = power_transform(score_brut)
    if score_final < 0.30: niveau = "Faible"
    elif score_final < 0.55: niveau = "Modéré"
    elif score_final < 0.75: niveau = "Élevé"
    else: niveau = "Critique"
    return pd.Series({'Score_Prédictif': score_final, 'Niveau_Risque': niveau})


df1[['Score_Prédictif', 'Niveau_Risque']] = df1.apply(calculer_score_predictif, axis=1)
print('Score prédictif de maintenance recalculé.')

Score prédictif de maintenance recalculé.

## 6. Génération des Variables Logistiques, Financières et RH (niveau TRAJET)

Cette section enrichit le jeu de données avec des variables simulées
nécessaires au module de gestion logistique et financière (Phase 1
du plan de développement TruckMind), en complément des variables
techniques générées à la section 5.

**Variables financières (par véhicule) :**
- Valeur d'achat simulée (MAD)
- Catégorie d'âge (Neuf / Jeune / Moyen / Ancien), basée sur les heures d'utilisation
- Distance totale estimée parcourue (km), dérivée des heures d'utilisation et du type de route
- Coût total de carburant (MAD), basé sur la consommation réelle et un prix de 13,20 MAD/L
- Revenu total estimé (MAD), basé sur le fret transporté (tonnage × distance × tarif de base),
  ajusté par un facteur d'âge du véhicule et par un facteur propre au type de marchandise transportée
- Valeur actuelle (MAD), après dépréciation linéaire sur une durée de vie de 30 000 heures
- Rentabilité nette (MAD) = revenu - coûts (entretien, carburant, dépréciation)

**Variables liées à la marchandise transportée :**
- Type de marchandise (12 catégories : matériaux de construction, produits alimentaires frais,
  produits chimiques, textiles, véhicules et pièces détachées, marchandises générales, produits
  agricoles, électroménager et électronique, produits pharmaceutiques, produits pétroliers,
  bois et matériaux forestiers, métaux et produits sidérurgiques)
- Facteur de tarification associé (marchandises à forte valeur ou sensibles facturées à un
  tarif premium ; marchandises en vrac à faible valeur facturées à un tarif réduit)
- Indicateur de marchandise dangereuse (produits chimiques, produits pétroliers), destiné à
  une utilisation future dans le système de notifications (Phase 3)

**Variables liées au chauffeur :**
- Identifiant, nom complet (données fictives)
- Années d'expérience, salaire de base mensuel
- Numéro et catégorie de permis de conduire, date d'expiration
- Prime d'activité cumulée, liée aux heures d'utilisation du véhicule assigné

**Variables liées au trajet :**
- Nom de l'itinéraire réel (référentiel de routes marocaines)
- Distance et durée estimées de l'itinéraire

*Note méthodologique : l'ensemble de ces variables sont des données simulées
à des fins académiques (absence de télémétrie réelle à ce stade du projet),
construites de manière cohérente entre elles (ex. le coût carburant et le
revenu partagent la même base de calcul : distance parcourue × charge
transportée, avec des facteurs d'ajustement liés à l'âge du véhicule et
au type de marchandise).*

In [40]:
# --- Distance & carburant du trajet -----------------------------------
vitesses_moyennes = {'autoroute': 80, 'urbain': 25, 'rural': 55}
df1['Distance_Totale_Estimee_Km'] = df1['Heures_Utilisation'] * df1['Info_Itinéraire'].map(vitesses_moyennes)
df1['Carburant_Total_Estime_Litres'] = df1['Distance_Totale_Estimee_Km'] / 100 * df1['Consommation_Carburant']
df1['Cout_Carburant_Total_MAD'] = df1['Carburant_Total_Estime_Litres'] * PRIX_CARBURANT_MAD_L

# --- Dépréciation (basée sur Valeur_Achat_MAD FIXE du véhicule) -------
df1['Valeur_Actuelle_MAD'] = (
    df1['Valeur_Achat_MAD'] * (1 - df1['Heures_Utilisation'] / DUREE_VIE_HEURES)
).clip(lower=df1['Valeur_Achat_MAD'] * 0.1)

In [41]:
# 11. ★ NOUVEAU ★ — RÉFÉRENTIEL EMPLOYÉS FINANCE / LOGISTIQUE

np.random.seed(SEED_BASE + 4)

prenoms_emp = ['Salma', 'Nadia', 'Imane', 'Fatima-Ezzahra', 'Meryem', 'Karima', 'Loubna',
               'Yassmine', 'Hanane', 'Siham', 'Amine', 'Othman', 'Younes', 'Karim', 'Rachid',
               'Abdelilah', 'Mounir', 'Samir', 'Nawal', 'Asmae']
noms_famille_emp = ['El Fassi', 'Bennouna', 'Tahiri', 'Chakiri', 'Bencherki', 'Idrissi',
                     'Amrani', 'Zniber', 'Berrada', 'Lamrani', 'Ghazi', 'Sekkat', 'Ouahbi',
                     'Rifki', 'Bouabid']

departements = ['Finance', 'Logistique']
postes = {
    'Finance'   : ['Contrôleur de Gestion', 'Analyste Financier', 'Responsable Facturation'],
    'Logistique': ['Planificateur de Tournées', 'Responsable Exploitation', 'Coordinateur Flotte'],
}

N_EMPLOYES = 25
toutes_combos_emp = list(itertools.product(prenoms_emp, noms_famille_emp))
idx_emp = np.random.choice(len(toutes_combos_emp), N_EMPLOYES, replace=False)
noms_emp = [f"{toutes_combos_emp[i][0]} {toutes_combos_emp[i][1]}" for i in idx_emp]

dept_choisis = np.random.choice(departements, size=N_EMPLOYES, p=[0.45, 0.55])
poste_choisis = [np.random.choice(postes[d]) for d in dept_choisis]

employes_ref = pd.DataFrame({
    'Employe_ID'  : ['E' + str(i).zfill(3) for i in range(1, N_EMPLOYES + 1)],
    'Employe_Nom' : noms_emp,
    'Departement' : dept_choisis,
    'Poste'       : poste_choisis,
})

df1['Employe_ID'] = np.random.choice(employes_ref['Employe_ID'], size=len(df1))
df1 = df1.merge(employes_ref, on='Employe_ID', how='left')

print(f'\nRéférentiel employés créé : {N_EMPLOYES} employés '
      f'({(dept_choisis == "Finance").sum()} Finance / {(dept_choisis == "Logistique").sum()} Logistique).')

Référentiel employés créé : 25 employés (14 Finance / 11 Logistique).

In [42]:
# 12. RÉFÉRENTIEL CHAUFFEURS (150) — inchangé, niveau TRAJET

np.random.seed(SEED_BASE + 5)

prenoms = ['Youssef', 'Karim', 'Mohamed', 'Hicham', 'Rachid', 'Said', 'Omar', 'Hamid', 'Aziz',
           'Khalid', 'Abdellah', 'Mustapha', 'Anas', 'Younes', 'Nabil', 'Tarik', 'Reda', 'Adil',
           'Jamal', 'Mehdi', 'Yassine', 'Amine', 'Soufiane', 'Hassan', 'Driss', 'Zakaria',
           'Othmane', 'Bilal', 'Ismail', 'Fouad']
noms_famille = ['El Amrani', 'Bennani', 'Chraibi', 'Idrissi', 'Tazi', 'Fassi', 'Alaoui',
                'Benjelloun', 'Ouazzani', 'Berrada', 'Kabbaj', 'Cherkaoui', 'Sqalli', 'Bennis',
                'Ziani', 'Lahlou', 'Mernissi', 'Sebti', 'Guessous', 'Belghazi', 'Rifai', 'Skalli',
                'Bouzidi', 'Naciri', 'Zerouali', 'Hajji', 'Toumi', 'Belhaj', 'Amrani', 'Sabir']

N_CHAUFFEURS = 150
toutes_combos = list(itertools.product(prenoms, noms_famille))
idx_choisis = np.random.choice(len(toutes_combos), N_CHAUFFEURS, replace=False)
noms_complets = [f"{toutes_combos[i][0]} {toutes_combos[i][1]}" for i in idx_choisis]

chauffeurs_ref = pd.DataFrame({
    'Chauffeur_ID'                : ['D' + str(i).zfill(3) for i in range(1, N_CHAUFFEURS + 1)],
    'Chauffeur_Nom'               : noms_complets,
    'Chauffeur_Experience_Annees' : np.random.randint(1, 26, size=N_CHAUFFEURS),
    'Permis_Numero'               : ['PC-' + str(np.random.randint(100000, 999999)) for _ in range(N_CHAUFFEURS)],
    'Permis_Categorie'            : np.random.choice(['C', 'CE'], size=N_CHAUFFEURS, p=[0.4, 0.6]),
    'Permis_Date_Expiration'      : pd.to_datetime('2026-07-22') + pd.to_timedelta(
        np.random.randint(-200, 1800, size=N_CHAUFFEURS), unit='D'),
})
chauffeurs_ref['Salaire_Base_Mensuel_MAD'] = 4000 + 150 * chauffeurs_ref['Chauffeur_Experience_Annees']

np.random.seed(SEED_BASE + 6)
df1['Chauffeur_ID'] = np.random.choice(chauffeurs_ref['Chauffeur_ID'], size=len(df1))
df1 = df1.merge(chauffeurs_ref, on='Chauffeur_ID', how='left')
df1['Prime_Activite_MAD'] = df1['Heures_Utilisation'] * TAUX_PRIME_PAR_HEURE

In [43]:
# 13. ROUTES (référentiel intégré) — inchangé, niveau TRAJET

routes_maroc = {
    'autoroute': [
        ('Tanger - Casablanca', 340, 4.0), ('Casablanca - Marrakech', 240, 3.0),
        ('Rabat - Fès', 200, 2.5), ('Casablanca - Agadir', 460, 5.5),
        ('Marrakech - Agadir', 250, 3.2), ('Casablanca - El Jadida', 95, 1.3),
        ('Fès - Oujda', 320, 4.2), ('Tanger - Rabat', 250, 3.0),
    ],
    'urbain': [
        ('Casablanca - Centre Ville', 15, 1.0), ('Tanger - Zone Industrielle', 10, 0.8),
        ('Rabat - Salé', 12, 0.9), ('Marrakech - Menara', 8, 0.6),
        ('Fès - Ville Nouvelle', 14, 1.1), ('Agadir - Centre', 11, 0.9),
    ],
    'rural': [
        ('Essaouira - Chichaoua', 90, 2.0), ('Taza - Oujda', 220, 4.0),
        ('Béni Mellal - Azilal', 85, 2.2), ('Ouarzazate - Zagora', 165, 3.5),
        ('Chefchaouen - Ouezzane', 60, 1.8), ('Sefrou - Boulemane', 70, 2.0),
    ],
}
np.random.seed(SEED_BASE + 7)


def choisir_route(type_route):
    options = routes_maroc[type_route]
    return options[np.random.randint(len(options))]


resultats = df1['Info_Itinéraire'].apply(choisir_route)
df1['Route_Nom']             = resultats.apply(lambda x: x[0])
df1['Route_Distance_Km']     = resultats.apply(lambda x: x[1])
df1['Route_Duree_Estimee_H'] = resultats.apply(lambda x: x[2])

In [44]:
# 14. ★ ÉTENDU ★ — TYPES DE MARCHANDISE (16 catégories au lieu de 12)

np.random.seed(SEED_BASE + 8)

types_marchandise = [
    'Matériaux de construction', 'Produits alimentaires (frais)', 'Produits chimiques',
    'Textiles', 'Véhicules et pièces détachées', 'Marchandises générales',
    'Produits agricoles', 'Électroménager et électronique', 'Produits pharmaceutiques',
    'Produits pétroliers', 'Bois et matériaux forestiers', 'Métaux et produits sidérurgiques',
    # --- 4 nouvelles catégories ---
    'Denrées en vrac (céréales)', 'Produits de la pêche',
    'Matériel médical et hospitalier', 'Meubles et ameublement',
]

# Probabilités recalibrées pour le marché marocain (somme = 1.0)
probabilites = [
    0.13, 0.11, 0.06, 0.08, 0.07, 0.11,   # 6 premières (légèrement réduites)
    0.08, 0.03, 0.03, 0.05, 0.04, 0.04,   # 6 suivantes
    0.07, 0.04, 0.02, 0.04,               # 4 nouvelles
]
assert abs(sum(probabilites) - 1.0) < 1e-9, "Les probabilités doivent sommer à 1.0"

facteurs_marchandise = {
    'Matériaux de construction':        0.90,
    'Produits alimentaires (frais)':    1.20,
    'Produits chimiques':               1.35,
    'Textiles':                         1.00,
    'Véhicules et pièces détachées':    1.15,
    'Marchandises générales':           1.00,
    'Produits agricoles':               0.85,
    'Électroménager et électronique':   1.25,
    'Produits pharmaceutiques':         1.50,
    'Produits pétroliers':              1.30,
    'Bois et matériaux forestiers':     0.80,
    'Métaux et produits sidérurgiques': 0.95,
    # --- nouvelles catégories ---
    'Denrées en vrac (céréales)':       0.75,  # vrac, très faible valeur/tonne
    'Produits de la pêche':             1.30,  # chaîne du froid stricte, périssable
    'Matériel médical et hospitalier':  1.45,  # forte valeur, réglementé, fragile
    'Meubles et ameublement':           1.05,  # volumineux, manutention soignée
}

df1['Type_Marchandise']    = np.random.choice(types_marchandise, size=len(df1), p=probabilites)
df1['Facteur_Marchandise'] = df1['Type_Marchandise'].map(facteurs_marchandise)

# Marchandise dangereuse (utile Phase 3 — notifications prioritaires)
marchandises_dangereuses = ['Produits chimiques', 'Produits pétroliers']
df1['Marchandise_Dangereuse'] = df1['Type_Marchandise'].isin(marchandises_dangereuses)

print('\nRépartition des types de marchandise :')
print(df1['Type_Marchandise'].value_counts())

Répartition des types de marchandise :
Type_Marchandise
Matériaux de construction           465
Produits alimentaires (frais)       410
Marchandises générales              370
Textiles                            301
Produits agricoles                  293
Denrées en vrac (céréales)          262
Véhicules et pièces détachées       261
Produits chimiques                  209
Produits pétroliers                 177
Produits de la pêche                161
Bois et matériaux forestiers        152
Métaux et produits sidérurgiques    144
Meubles et ameublement              144
Électroménager et électronique      100
Produits pharmaceutiques             93
Matériel médical et hospitalier      76
Name: count, dtype: int64

In [45]:
# 15. REVENU ET RENTABILITÉ (calcul final, avec Facteur_Age + Facteur_Marchandise)

df1['Revenu_Total_Estime_MAD'] = (
    df1['Charge_Réelle'] * df1['Distance_Totale_Estimee_Km']
    * PRIX_PAR_TONNE_KM_MAD * df1['Facteur_Age'] * df1['Facteur_Marchandise']
)

df1['Rentabilite_Nette_MAD'] = (
    df1['Revenu_Total_Estime_MAD']
    - df1['Coût_Entretien']
    - df1['Cout_Carburant_Total_MAD']
    - (df1['Valeur_Achat_MAD'] - df1['Valeur_Actuelle_MAD'])
)

print(f"\n% de trajets rentables : {(df1['Rentabilite_Nette_MAD'] > 0).mean() * 100:.1f}%")

% de trajets rentables : 94.7%

## 7. Vérification Finale et Export

Contrôle visuel du DataFrame nettoyé avant export au format CSV.

In [47]:
print('\n' + '=' * 60)
print('VÉRIFICATIONS DE COHÉRENCE')
print('=' * 60)

# Un même véhicule doit avoir EXACTEMENT une seule valeur de
# Capacité_Charge / Valeur_Achat_MAD / Année_Fabrication sur tous ses trajets
verif = df1.groupby('Identifiant_Véhicule')[['Capacité_Charge', 'Valeur_Achat_MAD', 'Année_Fabrication']].nunique()
incoherents = (verif > 1).any(axis=1).sum()
print(f'Véhicules avec attributs fixes incohérents entre trajets : {incoherents} (doit être 0)')

print(f'Nombre de véhicules uniques   : {df1["Identifiant_Véhicule"].nunique()} / {N_VEHICULES}')
print(f'Nombre de trajets (lignes)    : {len(df1)}')
print(f'Nombre de chauffeurs utilisés : {df1["Chauffeur_ID"].nunique()} / {N_CHAUFFEURS}')
print(f'Nombre d\'employés utilisés    : {df1["Employe_ID"].nunique()} / {N_EMPLOYES}')
print(f'Nombre de routes uniques      : {df1["Route_Nom"].nunique()}')
print(f'Nombre de types de marchandise: {df1["Type_Marchandise"].nunique()} / 16')

============================================================
VÉRIFICATIONS DE COHÉRENCE
============================================================
Véhicules avec attributs fixes incohérents entre trajets : 0 (doit être 0)
Nombre de véhicules uniques   : 1000 / 1000
Nombre de trajets (lignes)    : 3618
Nombre de chauffeurs utilisés : 150 / 150
Nombre d'employés utilisés    : 25 / 25
Nombre de routes uniques      : 20
Nombre de types de marchandise: 16 / 16

In [48]:
# 17. RÉORGANISATION DES COLONNES 

colonnes_ordre = [
    # Identifiants
    'Trajet_ID', 'Identifiant_Véhicule',
    # Attributs fixes du véhicule
    'Année_Fabrication', 'Capacité_Charge', 'Valeur_Achat_MAD', 'Valeur_Actuelle_MAD',
    'Categorie_Age', 'Facteur_Age',
    # Trajet / usage
    'Heures_Utilisation', 'Charge_Réelle', 'Date_Dernier_Entretien',
    'Info_Itinéraire', 'Conditions_Route', 'Conditions_Météo',
    'Route_Nom', 'Route_Distance_Km', 'Route_Duree_Estimee_H',
    'Distance_Totale_Estimee_Km',
    # Maintenance
    'Type_Entretien', 'Coût_Entretien', 'Entretien_Nécessaire',
    'Délais_Livraison', 'Temps_Arrêt_Entretien', 'Impact_Efficacité',
    # Capteurs
    'Température_Moteur', 'Pression_Pneus', 'Consommation_Carburant',
    'État_Batterie', 'Niveaux_Vibration', 'Qualité_Huile', 'État_Freins',
    'Historique_Pannes', 'Anomalies_Détectées',
    'Score_Prédictif', 'Niveau_Risque',
    # Marchandise
    'Type_Marchandise', 'Facteur_Marchandise', 'Marchandise_Dangereuse',
    # Finance
    'Carburant_Total_Estime_Litres', 'Cout_Carburant_Total_MAD',
    'Revenu_Total_Estime_MAD', 'Rentabilite_Nette_MAD',
    # Chauffeur
    'Chauffeur_ID', 'Chauffeur_Nom', 'Chauffeur_Experience_Annees',
    'Permis_Numero', 'Permis_Categorie', 'Permis_Date_Expiration',
    'Salaire_Base_Mensuel_MAD', 'Prime_Activite_MAD',
    # Employé Finance/Logistique responsable du trajet
    'Employe_ID', 'Employe_Nom', 'Departement', 'Poste',
]

# Sécurité : ne garder que les colonnes réellement présentes, dans l'ordre voulu
colonnes_finales = [c for c in colonnes_ordre if c in df1.columns]
colonnes_restantes = [c for c in df1.columns if c not in colonnes_finales]
df1 = df1[colonnes_finales + colonnes_restantes]

In [49]:
# --- Export du DataFrame nettoyé au format CSV ---
# Le fichier résultant servira de base au système RAG.

import os
script_dir = os.path.dirname(os.path.abspath("__file__"))
project_root = os.path.dirname(script_dir)
OUTPUT_CSV = os.path.join(project_root, "uploads", "truckmind_dataset_complet.csv")
df1.to_csv(OUTPUT_CSV, index=False)
print(f'Jeu de données exporté : {OUTPUT_CSV} ({len(df1)} lignes, {len(df1.columns)} colonnes)')

Jeu de données exporté : e:\1er_projet_de_maitenance_predicitive\uploads\truckmind_dataset_complet.csv (3618 lignes, 54 colonnes)

In [50]:
# --- Aperçu des 15 premières observations du DataFrame nettoyé ---
df1.head(15)

,Trajet_ID,Identifiant_Véhicule,Année_Fabrication,Capacité_Charge,Valeur_Achat_MAD,Valeur_Actuelle_MAD,Categorie_Age,Facteur_Age,Heures_Utilisation,Charge_Réelle,...,Chauffeur_Experience_Annees,Permis_Numero,Permis_Categorie,Permis_Date_Expiration,Salaire_Base_Mensuel_MAD,Prime_Activite_MAD,Employe_ID,Employe_Nom,Departement,Poste
0,T00001,V0979,2011,27.553428,1042289.0,9.893407e+05,Ancien,0.80,1524,24.294535,...,18,PC-899608,CE,2029-11-21,6700,762.0,E014,Siham Amrani,Logistique,Responsable Exploitation
1,T00002,V0729,2012,25.014646,1229799.0,1.185608e+06,Ancien,0.80,1078,28.847604,...,24,PC-288221,CE,2029-12-04,7600,539.0,E007,Loubna Ghazi,Logistique,Planificateur de Tournées
2,T00003,V0737,2020,22.156752,1047854.0,1.029831e+06,Moyen,0.95,516,20.019576,...,17,PC-514691,CE,2030-11-20,6550,258.0,E015,Hanane Rifki,Finance,Responsable Facturation
3,T00004,V0244,2022,26.340057,960256.0,9.077620e+05,Jeune,1.05,1640,19.915936,...,5,PC-152821,C,2027-08-26,4750,820.0,E020,Nawal Sekkat,Logistique,Responsable Exploitation
4,T00005,V0444,2010,26.070940,1245725.0,1.025481e+06,Ancien,0.80,5304,21.923719,...,20,PC-105899,C,2029-07-27,7000,2652.0,E017,Loubna Idrissi,Finance,Analyste Financier
5,T00006,V0160,2022,28.226006,1055813.0,9.572001e+05,Jeune,1.05,2802,22.938665,...,20,PC-105899,C,2029-07-27,7000,1401.0,E001,Yassmine Tahiri,Finance,Responsable Facturation
6,T00007,V0612,2022,22.221078,1282110.0,1.198687e+06,Jeune,1.05,1952,23.352136,...,3,PC-451515,C,2026-08-23,4450,976.0,E020,Nawal Sekkat,Logistique,Responsable Exploitation
7,T00008,V0942,2021,23.109823,924981.0,6.844551e+05,Jeune,1.05,7801,19.355228,...,8,PC-608719,C,2027-08-20,5200,3900.5,E019,Younes Ghazi,Logistique,Coordinateur Flotte
8,T00009,V0166,2021,24.921163,1094848.0,1.010070e+06,Jeune,1.05,2323,25.975483,...,10,PC-882078,CE,2029-05-08,5500,1161.5,E023,Yassmine Ouahbi,Finance,Responsable Facturation
9,T00010,V0054,2012,29.252483,961494.0,9.490587e+05,Ancien,0.80,388,33.890110,...,1,PC-974067,C,2028-06-01,4150,194.0,E009,Fatima-Ezzahra Rifki,Finance,Responsable Facturation
10,T00011,V0571,2020,27.891712,1273829.0,1.180287e+06,Moyen,0.95,2203,20.767590,...,16,PC-961501,CE,2028-12-19,6400,1101.5,E011,Nadia Sekkat,Finance,Responsable Facturation
11,T00012,V0304,2021,22.632011,1289029.0,1.057777e+06,Jeune,1.05,5382,26.212383,...,21,PC-795011,C,2030-11-13,7150,2691.0,E019,Younes Ghazi,Logistique,Coordinateur Flotte
12,T00013,V0585,2022,29.899602,1123232.0,9.533619e+05,Jeune,1.05,4537,25.814931,...,8,PC-778439,CE,2030-11-05,5200,2268.5,E023,Yassmine Ouahbi,Finance,Responsable Facturation
13,T00014,V0538,2014,29.912560,1077847.0,9.675473e+05,Ancien,0.80,3070,24.272107,...,15,PC-725938,CE,2028-10-03,6250,1535.0,E022,Abdelilah El Fassi,Finance,Analyste Financier
14,T00015,V0047,2020,21.732943,1178972.0,8.571126e+05,Moyen,0.95,8190,18.338313,...,16,PC-467784,CE,2028-07-05,6400,4095.0,E006,Rachid Bennouna,Logistique,Responsable Exploitation

In [51]:
# --- Statistiques descriptives des variables catégorielles ---
df1.describe(include='object')

,Trajet_ID,Identifiant_Véhicule,Categorie_Age,Info_Itinéraire,Conditions_Route,Conditions_Météo,Route_Nom,Type_Entretien,État_Freins,Niveau_Risque,Type_Marchandise,Chauffeur_ID,Chauffeur_Nom,Permis_Numero,Permis_Categorie,Employe_ID,Employe_Nom,Departement,Poste
count,3618,3618,3618,3618,3618,3618,3618,3618,3618,3618,3618,3618,3618,3618,3618,3618,3618,3618,3618
unique,3618,1000,3,3,3,4,20,3,3,4,16,150,150,150,2,25,25,2,6
top,T00001,V0225,Jeune,autoroute,autoroute,clair,Rabat - Fès,changement d'huile,bon,Élevé,Matériaux de construction,D079,Soufiane Bennis,PC-938635,CE,E006,Rachid Bennouna,Finance,Responsable Facturation
freq,1,10,1360,1825,1421,2926,249,1660,1824,1626,465,40,40,40,2250,174,174,1931,963

In [52]:
# --- Statistiques descriptives des variables numériques (float) ---
df1.describe(include='float64')

,Capacité_Charge,Valeur_Achat_MAD,Valeur_Actuelle_MAD,Facteur_Age,Charge_Réelle,Route_Duree_Estimee_H,Coût_Entretien,Délais_Livraison,Temps_Arrêt_Entretien,Impact_Efficacité,...,État_Batterie,Niveaux_Vibration,Qualité_Huile,Score_Prédictif,Facteur_Marchandise,Carburant_Total_Estime_Litres,Cout_Carburant_Total_MAD,Revenu_Total_Estime_MAD,Rentabilite_Nette_MAD,Prime_Activite_MAD
count,3618.000000,3.618000e+03,3.618000e+03,3618.000000,3618.000000,3618.000000,3618.000000,3618.000000,3618.000000,3618.000000,...,3618.000000,3618.000000,3618.000000,3618.000000,3618.000000,3.618000e+03,3.618000e+03,3.618000e+03,3.618000e+03,3618.000000
mean,28.237116,1.104694e+06,9.948012e+05,0.939580,26.744730,2.546877,1020.555969,99.308937,3.251591,0.209092,...,77.106108,7.040854,79.439685,0.591867,1.059439,8.507696e+04,1.123016e+06,2.395842e+06,1.161913e+06,1488.826009
std,7.747569,1.152508e+05,1.514582e+05,0.104187,8.496228,1.362917,1553.867511,79.971701,6.593442,0.111409,...,10.227753,2.588527,9.806641,0.169982,0.200097,1.034601e+05,1.365673e+06,3.058246e+06,1.893068e+06,1518.587514
min,20.010818,9.001460e+05,9.196050e+04,0.800000,14.098869,0.600000,100.223731,30.000000,0.000000,0.100000,...,43.800000,1.000000,43.176358,0.062900,0.750000,0.000000e+00,0.000000e+00,0.000000e+00,-2.276221e+06,0.000000
25%,22.896483,1.008624e+06,8.987288e+05,0.800000,20.986255,1.300000,229.508521,30.000000,0.000000,0.105212,...,70.100000,5.110000,72.927933,0.477800,0.900000,1.979238e+04,2.612594e+05,5.184260e+05,1.357331e+05,417.500000
50%,26.075449,1.103750e+06,9.975278e+05,0.950000,24.678874,2.500000,349.593575,69.186799,0.000000,0.179810,...,77.600000,7.020000,79.346645,0.608750,1.000000,5.114184e+04,6.750723e+05,1.334272e+06,5.037426e+05,1001.250000
75%,29.499612,1.203012e+06,1.108494e+06,1.050000,29.876028,3.500000,471.906150,138.781838,3.671181,0.272367,...,84.400000,8.900000,86.193171,0.718175,1.200000,1.104624e+05,1.458104e+06,3.059231e+06,1.362847e+06,2090.000000
max,54.907159,1.299506e+06,1.291012e+06,1.050000,64.635410,5.500000,5999.042959,300.000000,73.668632,0.741097,...,100.000000,12.000000,100.000000,0.993800,1.500000,1.260072e+06,1.663295e+07,3.456004e+07,2.477156e+07,14319.000000

In [53]:
# --- Export du DataFrame nettoyé au format CSV ---
# Le fichier résultant servira de base au système RAG.

OUTPUT_CSV = r'E:\1er_projet_de_maitenance_predicitive\uploads\truckmind_dataset_complet.csv'
df1.to_csv(OUTPUT_CSV, index=False)
print(f'Exporté : {OUTPUT_CSV} ({len(df1)} lignes, {len(df1.columns)} colonnes)')

Exporté : E:\1er_projet_de_maitenance_predicitive\uploads\truckmind_dataset_complet.csv (3618 lignes, 54 colonnes)